ccfos/nightingale

etc/monapi.yml
src/model/ldap.go
src/model/user.go
src/modules/monapi/config/yaml.go

changelog
1. 支持首次 ldap 登录自动注册时，携带属性
2. 增加 attributes 配置属性映射关系
3. 增加 autoRegist 开关，控制是否允许 ldap 认证自动注册
4. 增加 coverAttributes，控制后续登录时，是否以 ldap 属性覆盖 uic 内的属性
5. 允许 ldap 匿名查询 (bindUser="")

优化 LDAP 认证部分的支持

---

src/modules/collector/log/reader/reader.go

see: https://godoc.org/os#SEEK_SET

os.SEEK_* is deprecated, use io.Seek* instead

---

src/modules/transfer/backend/pool.go
src/modules/transfer/backend/query.go
src/modules/transfer/backend/ring.go
src/modules/transfer/config/config.go
src/modules/transfer/cron/stra.go
src/modules/transfer/http/routes/push_router.go
src/toolkits/stats/init.go

* redesign the logic of fetching data

performance improvement

---

README.md
README_ZH.md

ping @710leo @UlricQin Yet another PR for the Nightingale community

Documents for the Nightingale community

---

src/modules/index/cache/counter_map.go
src/modules/index/cache/endpoint_map.go
src/modules/index/cache/endpoints.go
src/modules/index/cache/indexdb.go
src/modules/index/cache/metric_map.go
src/modules/index/cache/tag.go
src/modules/index/cache/tag_map.go
src/modules/index/http/routes/index_router.go
src/modules/index/rpc/push.go

@710leo I get some questions after reading the index-module source code. Could I discuss them with you?

Review index module

---

src/modules/judge/judge/nodata.go

nodata judgeItem tagMap

---

src/modules/collector/log/reader/reader.go
src/modules/collector/log/reader/reader_util.go
src/modules/collector/log/reader/reader_util_test.go
src/modules/collector/log/worker/control.go
src/modules/collector/log/worker/control_test.go
src/modules/collector/log/worker/worker.go

* WIP: there is something needs to discuss

Try to fix broken tests

---

.gitignore
web/src/pages/Monitor/Collect/CollectForm/PORTForm.tsx

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix
* **What is the current behavior?** (You can also link to an open issue here)
#109 
* **What is the new behavior (if this is a feature change)?**
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
* **Other information**:
add yarn.lock to .gitignore

service regular fix

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
feature
* **What is the current behavior?** (You can also link to an open issue here)
* **What is the new behavior (if this is a feature change)?**
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
* **Other information**:

Add issue template

---

src/modules/collector/config/config.go
src/modules/collector/log/worker/cached.go
src/modules/collector/log/worker/counter.go
src/modules/collector/log/worker/worker.go

No 'this' anymore

---

control
src/modules/collector/collector.go
src/modules/index/index.go
src/modules/judge/judge.go
src/modules/monapi/monapi.go
src/modules/transfer/transfer.go
src/modules/tsdb/tsdb.go

Supports a better approach for managing modules version.
Fixes #134 
Here is the recommended workflow for releasing a new version:
1. Update the global `version` variable in `control` file.
2. Create a new PR(or just push a release commit directly). Anyway, there should be one specified commit for the version release.
3. Create a new release on GitHub (https://github.com/didi/nightingale/releases) and perfect the release notes(changelog).
Version info as below
```
~/project/golang/src/github.com/didi/nightingale 🐶 .f/n9e-transfer -v  
2020/05/11 19:50:12 maxprocs: Leaving GOMAXPROCS=12: CPU quota undefined
Version: 1.3.3
Git Commit Hash: …
```

Version management

---

etc/transfer.yml
src/dataobj/influxdb.go
src/modules/transfer/backend/init.go
src/modules/transfer/backend/sender.go
src/modules/transfer/config/config.go
src/modules/transfer/rpc/push.go

支持transfer一份数据到influxdb，参照open-falcon代码，按照n9e的一些规范，做了相应调整
使用
`
wget https://dl.influxdata.com/influxdb/releases/influxdb-1.8.0.x86_64.rpm
sudo yum localinstall influxdb-1.8.0.x86_64.rpm
systemctl start influxdb
systemctl enable influxdb
[root@localhost nightingale]# influx
Connected to http://localhost:8086 version 1.8.0
InfluxDB shell version: 1.8.0
> CREATE USER influx WITH PASSWORD admin123 WITH ALL PRIVILEGES
> CREATE DATABASE n9e
修改transfer.yml
将enabled改为true
`

support send to influxdb

---

src/modules/collector/stra/log.go
src/modules/monapi/http/routes/collect.go

Add log time format 02 / 01 / 2006:15:04:05

Add log time format 02 / 01 / 2006:15:04:05

---

src/modules/monapi/http/routes/collect.go

Server Add log time format 02 / 01 / 2006:15:04:05

Server Add log time format 02 / 01 / 2006:15:04:05

---

src/modules/judge/judge/func.go

Feature
Add stddev function for judge.
Fixes #211

Add stddev function for judge

---

src/modules/judge/judge/func.go
src/modules/judge/judge/judge.go

Fix stddev function

---

web/src/components/Exception/Page403.tsx

Page403.tsx的组件名写成404了！

---

src/modules/collector/collector.go
src/modules/collector/core/clients.go
src/modules/collector/core/common.go
src/modules/collector/core/push.go
src/modules/collector/http/routes/api_router.go
src/modules/collector/log/worker/push.go
src/modules/collector/sys/funcs/collector.go
src/modules/collector/sys/funcs/cpustat.go
src/modules/collector/sys/funcs/cron.go
src/modules/collector/sys/funcs/dfstat.go
src/modules/collector/sys/funcs/diskstat.go
src/modules/collector/sys/funcs/fsstat.go
src/modules/collector/sys/funcs/ifstat.go
src/modules/collector/sys/funcs/loadavg.go
src/modules/collector/sys/funcs/meminfo.go
src/modules/collector/sys/funcs/netfilter.go
src/modules/collector/sys/funcs/ntp.go
src/modules/collector/sys/funcs/snmp.go
src/modules/collector/sys/funcs/sockstas.go
src/modules/collector/sys/funcs/sys.go
src/modules/collector/sys/plugins/scheduler.go
src/modules/collector/sys/ports/scheduler.go
src/modules/collector/sys/procs/scheduler.go

重构collector模块，push 相关功能从sys抽取到core。

refactor collect push , sys -> core

---

etc/collector.yml
src/modules/collector/config/config.go
src/modules/collector/sys/config.go
src/modules/collector/sys/funcs/funcs.go

collector 支持配置sys是否采集物理机指标，默认 enable: true
enable: false 仅上报 proc.agent.alive 指标

collect config sys enable,default true

---

src/model/endpoint.go

更改代码顺序，提高代码性能

---

src/dataobj/metric.go

fix: misspelling

---

src/toolkits/stats/init.go

Configure collector push address
Container deployment

Configure collector push address

---

src/toolkits/stats/init.go

支持容器化部署配置自监控，兼容之前的配置

---

dockerfiles/n9e/entrpoint.sh

remove duplicate RDB sql

---

etc/rdb.yml
src/modules/rdb/config/yaml.go
src/modules/rdb/http/router.go
src/modules/rdb/http/router_auth.go
src/modules/rdb/ssoc/sso.go

support openID2.0

---

.gitignore
etc/rdb.yml
src/models/user.go
src/modules/rdb/config/yaml.go
src/modules/rdb/http/router.go
src/modules/rdb/http/router_auth.go
src/modules/rdb/ssoc/sso.go

[ADD]  generate UUID if it's not set

---

go.mod
src/modules/job/http/router_task.go

tt invoke job api， and job callback async

support tt automation by job

---

src/modules/rdb/http/router.go
src/modules/rdb/http/router_resource.go

rdb资源cate分类统计接口

---

dockerfiles/n9e/Dockerfile

fix redis connection

---

dockerfiles/n9e/Dockerfile
dockerfiles/n9e/entrpoint.sh

sed ip to host  for docker

---

src/modules/rdb/http/router_resource.go

rdb统计资源增加volume

---

etc/transfer.yml
src/common/dataobj/query_item.go
src/modules/transfer/backend/init.go
src/modules/transfer/backend/m3db/convert.go
src/modules/transfer/backend/m3db/m3db.go
src/modules/transfer/backend/m3db/query.go

validate ui query, add aggrFun support for resample

---

.gitignore
etc/rdb.yml
src/modules/transfer/backend/m3db/m3db.go
src/modules/transfer/backend/m3db/query.go
src/modules/transfer/backend/m3db/test/04-query-metrics.sh
src/modules/transfer/http/routes/query_router.go

support time limit for m3db query

---

sql/n9e_rdb.sql
src/models/user.go
src/modules/rdb/http/router_resource.go
src/modules/rdb/http/router_user.go

rdb新增用户添加时间

---

sql/n9e_rdb.sql
src/models/user.go
src/modules/rdb/http/router_resource.go
src/modules/rdb/http/router_user.go

rdb新增用户添加时间代码调整

---

src/models/user.go
src/models/user_service.go
src/modules/rdb/http/router.go
src/modules/rdb/http/router_user.go

support get users by org

---

src/modules/judge/judge/func.go

变化率绝对值算法问题

---

src/modules/monapi/http/router_event.go

monapi etime

---

src/modules/monapi/http/router_event.go

monapi hours参数支持

---

src/modules/rdb/http/router_tree.go

Nodename search

---

src/common/dataobj/query_item.go
src/modules/rdb/auth/authenticator.go
src/modules/rdb/http/router_auth.go
src/modules/rdb/session/session.go
src/modules/transfer/backend/m3db/m3db.go
src/modules/transfer/backend/m3db/query.go

- add start,end for transfer.index.fullmatch get

add start,end for transfer.index.fullmatch get

---

src/models/node_resource.go
src/modules/rdb/http/router.go
src/modules/rdb/http/router_resource.go

租户项目粒度某类资源top数量

---

src/modules/rdb/http/router_user.go

新增用户添加组织字段

---

src/modules/transfer/backend/m3db/m3db.go

m3db writetagged应该并发做，不然会导致transfer rpc变慢

---

src/modules/judge/judge.go
src/modules/monapi/config/yaml.go
src/modules/monapi/http/router.go
src/modules/monapi/http/router_tpl.go

Support screen and alert template
Fixes #

Support screen and alert template

---

src/models/resource.go
src/modules/ams/http/router.go
src/modules/ams/http/router_host.go

ams agent直接挂载到节点

---

sql/n9e_mon-patch.sql
sql/n9e_mon.sql
src/models/mon_aggr.go
src/models/mon_collect.go
src/models/mon_collect_rule.go
src/modules/monapi/collector/basecollector.go
src/modules/monapi/collector/template.go
src/modules/monapi/http/router.go
src/modules/monapi/http/router_collect.go
src/modules/monapi/plugins/all/all.go
src/modules/monapi/plugins/mongodb/mongodb.go
src/modules/monapi/plugins/mongodb/mongodb/mongodb.go
src/modules/monapi/plugins/mysql/mysql.go
src/modules/monapi/plugins/redis/redis.go
src/modules/monapi/plugins/util.go
src/modules/monapi/scache/collectrule.go
src/modules/prober/manager/collectrule.go
src/modules/prober/manager/heap.go
src/modules/prober/manager/manager.go
src/modules/prober/prober.go

- add logger with monapi.plugins as telegraf.Logger interface
- bugfix: prober.heap.top() should get first entity
- variable rename
* last_updator -> updater
* last_updated -> updatedAt
* created -> createdAt

add logger with monapi.plugins as telegraf.Logger interface

---

src/modules/agent/cache/cache.go
src/modules/agent/sys/procs/scheduler.go
src/modules/agent/sys/procs/sys.go

change proc info collect
Fixes #

change proc info collect

---

etc/prober.yml
src/common/report/report.go
src/models/mon_hbs.go
src/modules/monapi/plugins/redis/redis.go

- add mon.plugins.redis descriptions

add mon.plugins.redis descriptions

---

dockerfiles/n9e/Dockerfile

What type of PR is this?
这是什么类型的PR？
*  feat update go proxy module url
更新go代理模块地址(阿里云源的挂了)

update go proxy module url

---

etc/prober.yml
src/common/report/report.go
src/models/mon_collect_rule.go
src/models/mon_hbs.go
src/modules/monapi/http/router_collect.go
src/modules/monapi/plugins/redis/redis.go
src/modules/prober/manager/collectrule.go
src/modules/prober/manager/manager.go

bugfix: replace ref with instantiated variable for prober.rules.updatedAt

bugfix: replace ref with instantiated variable for prober.rules.updatedAt

---

src/modules/monapi/collector/basecollector.go
src/modules/prober/cache/collectrule.go

bugfix: return err when unable to get monapi.collectRule

bugfix: return err when unable to get monapi.collectRule

---

sql/n9e_mon.sql
src/models/mon_collect_rule.go

remove sql.mon.collect_rule.created

remove sql.mon.collect_rule.created

---

etc/address.yml
src/modules/prober/config/config.go
src/modules/prober/config/plugin.go

- remove prober RPC.port from config
- add a checker for prober.plugins.config.metrics

remove prober RPC.port from config

---

src/modules/rdb/http/router_resource.go

租户项目的资源排行去掉内置租户

---

go.mod
go.sum
src/common/address/address.go
src/modules/monapi/plugins/.gitignore
src/modules/monapi/plugins/all/all.go
src/modules/monapi/plugins/github/github_test.go
src/modules/monapi/plugins/prometheus/prometheus.go
src/modules/monapi/plugins/prometheus/prometheus/README.md
src/modules/monapi/plugins/prometheus/prometheus/kubernetes.go
src/modules/monapi/plugins/prometheus/prometheus/kubernetes_test.go
src/modules/monapi/plugins/prometheus/prometheus/parser.go
src/modules/monapi/plugins/prometheus/prometheus/parser_test.go
src/modules/monapi/plugins/prometheus/prometheus/prometheus.go
src/modules/monapi/plugins/prometheus/prometheus/prometheus_test.go
src/modules/monapi/plugins/prometheus/prometheus_test.go
src/modules/monapi/plugins/util.go
src/modules/prober/config/plugin.go
src/modules/prober/manager/accumulator.go
src/modules/prober/manager/collectrule.go
src/modules/prober/manager/manager.go

- add accumulator for prober
- generate default plugin config if config not exists

add accumulator for prober & generate default plugin config

---

src/modules/rdb/auth/authenticator.go
src/modules/rdb/session/session_db.go

- keep at least 4 history passwords
- adjust gc time for session

adjust session GC interval

---

src/modules/monapi/plugins/prometheus/prometheus_test.go
src/modules/prober/manager/manager_test.go
src/modules/rdb/http/router_auth.go

use testhttp instead of http for ut

---

src/modules/monapi/plugins/all/all.go
src/modules/monapi/plugins/demo/demo.go
src/modules/monapi/plugins/demo/demo/demo.go
src/modules/monapi/plugins/demo/demo_test.go
src/modules/monapi/plugins/prometheus/prometheus_test.go
src/modules/monapi/plugins/util.go
src/modules/prober/manager/manager_test.go

- add a demo plugin for prober

add a demo plugin for prober

---

src/modules/monapi/plugins/all/dlopen.go
src/modules/monapi/plugins/demo/lib/Makefile
src/modules/monapi/plugins/demo/lib/lib.go
src/modules/prober/prober.go

feature: support dlopen for prober plugin

---

.gitignore
src/modules/monapi/plugins/mysql/mysql_test.go
src/modules/prober/manager/metric.go

convert string yes, no, on, off, true, false, none to float64

fix: #583 convert string yes, no, on, off, true, false, none to float64

---

go.mod
src/models/mon_collect.go
src/models/mon_collect_rule.go
src/models/sso_token.go
src/modules/monapi/collector/basecollector.go
src/modules/monapi/http/router_collect.go
src/modules/monapi/monapi.go
src/modules/monapi/plugins/log/log.go
src/modules/monapi/plugins/plugin/plugin.go
src/modules/monapi/plugins/port/port.go
src/modules/monapi/plugins/proc/proc.go
src/modules/monapi/plugins/util.go
src/modules/prober/manager/accumulator/accumulator.go
src/modules/prober/manager/collectrule.go
src/modules/prober/manager/metric/metric.go

- feature: add dry run for collect_rule add/update

feature: add dryrun for collect_rule add/update

---

etc/plugins/dns_query.yml
src/modules/monapi/plugins/all/all.go
src/modules/monapi/plugins/dns_query/dns_query.go
src/modules/monapi/plugins/dns_query/dns_query_test.go

telegraf dns_query plugins

---

changelog
etc/screen/n9e_mudules

新增n9e模块监控大盘

---

src/modules/rdb/auth/authenticator.go

bugfix: auth password history size

bugfix: auth password history size

---

src/modules/prober/manager/collectrule.go
src/modules/prober/manager/manager.go

- bugfix: add prober.plugins Stop() for release resource

bugfix: add prober.plugins Stop() for release resource

---

src/modules/monapi/plugins/util.go

prettify msg

---

etc/rdb.yml
src/modules/rdb/config/yaml.go
src/modules/rdb/http/router_node.go

- feature: support node event notify with webhook

feature: support node event notify with webhook

---

src/modules/rdb/config/i18n.go
src/modules/rdb/http/router_auth.go

add subject for rdb rst-code/login-code mail

---

src/modules/rdb/auth/authenticator.go

bugfix: created_at -> create_at for rdb.user table

---

src/modules/prober/config/plugin.go

prober plugin use `all` mode as default

---

src/models/invite.go
src/modules/server/http/router_user.go

bugfix: use InviteMustGet instead of InviteGet

---

src/modules/server/notify/notify.go

bugfix 
wrong notifyType and subject when send alarm mail

fix: send mail not work(wrong notifyType and subject)

---

src/modules/server/http/router_user.go

bugfix: add user.Type

---

go.mod
go.sum
src/modules/prober/prober.go
src/modules/server/plugins/all/all.go
src/modules/server/plugins/http_response/http_response.go
src/modules/server/plugins/http_response/http_response/http_response.go
src/modules/server/plugins/postgresql/postgresql.go
src/modules/server/plugins/postgresql/postgresql/pg_setting.go
src/modules/server/plugins/postgresql/postgresql/postgresql.go
src/modules/server/plugins/postgresql/postgresql/service.go
src/modules/server/plugins/postgresql/postgresql/utils.go
src/modules/server/plugins/postgresql/postgresql_test.go
src/modules/server/server.go

功能新增
新增postgresql监控，修复http_response插件会将status_code附加在tag上的问题
Fixes #

新增postgresql监控

---

etc/agentd.yml
src/modules/agentd/config/config.go
src/modules/agentd/core/push.go
src/modules/agentd/sys/config.go
src/modules/agentd/sys/funcs/dfstat.go
src/modules/agentd/sys/funcs/fsstat.go

1.agent 增加默认tags功能,方便agentd区分和告警条件筛选;     2.agent 增加正则匹配磁盘挂载类型过滤功能，避免采集镜像iso等挂载目录

agent 增加默认tags功能, agent 增加正则匹配磁盘挂载类型过滤功能

---

src/modules/server/backend/m3db/benchmark/main.go
src/modules/server/backend/m3db/m3db.go

Fix logger.Errorf calls in src/modules/server/backend/m3db/m3db.go.

m3db: fix Errorf calls

---

etc/script/notify.py

1. notify.py 支持安装channel反射发送
2. 支持钉钉群发送
3. 生成告警模板信息
Fixes #

notify.py 脚本完善功能

---

etc/server.yml
src/modules/server/cron/sender_im.go
src/modules/server/feishu/feishu.go

向v4版本新增飞书告警模块
飞书逐渐被更多企业接受，但目前无法像飞书群发送告警，因此有必要新增飞书通知模块
Fixes #

V4.0.4 新增飞书通知模块

---

http/router_ts_data.go

fix: support gzip/zlib with series push

fix: support gzip/zlib with series push

---

http/http_middle.go
http/router_alert_rule_group.go
http/router_user.go
models/resource.go
models/role_operation.go
models/user.go

Multi roles support

---

backend/prome/query.go
vos/query.go

1. tag-pair support fuzzy matching search

tag-pair support fuzzy matching search

---

backend/prome/prome.go

1. fix remote write err assert on recoverableError

fix remote write err assert on recoverableError

---

backend/prome/query.go

in prometheus  this work done by the frontend.
but here is done by the backend

 1. query nodata at one ts fill none

---

backend/prome/query.go
judge/prome_pull.go
judge/query.go

remove some todo

---

http/router.go
http/router_alert_rule.go
models/alert_rule.go

feat:support batch edit notify groups of alert rule

---

judge/last_event.go

1. delete recovery event from cache  after event is really mark recovery

fix recovery alert bug

---

backend/prome/query.go

- fix CommonQuerySeries.Warning range nil pointer err
-  due to x.Error may be nil

fix CommonQuerySeries.Warning range nil pointer err

---

backend/prome/prome.go
backend/prome/query.go
config/config.go
etc/server.yml

1.  move the default ql to the configuration
2.  add slowLogRecordSecond to  log slow query 
3.  create a slice with a specified length to avoid dynamic expansion
4.  slow query print fetch series time took and the result series num

slow query limit

---

src/pkg/sys/cmd_unix.go
src/pkg/sys/cmd_windows.go
src/server/engine/notify.go

增加对windows的支持
Fixes #
在windows下启动会出现如下异常：

add windows support

---

src/models/dashboard.go

如果dashboard没有默认chart_group，会无法删除dashboard。
Fixes #

修复无法删除空dashboard问题

---

src/server/engine/notify.go

perf: optimize alert plugin call(#886)

---

etc/webapi.conf
go.mod
go.sum
src/models/user.go
src/pkg/oidcc/oidc.go
src/pkg/ssoc/sso.go
src/webapi/config/config.go
src/webapi/router/router.go
src/webapi/router/router_login.go
src/webapi/webapi.go

new feature
support oidc
Fixes #

feat: support OIDC

---

src/webapi/router/router_alert_cur_event.go

按告警级别和数量排序

---

src/webapi/router/router_mw.go

fix: err is nil

---

README.md
README_ZH.md
src/webapi/router/router_mw.go

doc: improve readme

---

etc/template/dingtalk.tpl
etc/template/mailbody.tpl

优化告警格式模板，增加**监控对象**字段，更方便定位机器。调整**触发时值**位置。

优化告警格式模板,增加 监控对象字段

---

src/webapi/config/i18n.go
src/webapi/router/router.go
src/webapi/router/router_login.go

use const http status text instead of a variable

use const http status text instead of a variable

---

Makefile
etc/server.conf
etc/webapi.conf
src/models/target.go
src/pkg/ormx/ormx.go
src/server/config/config.go
src/server/server.go
src/storage/storage.go
src/webapi/config/config.go
src/webapi/webapi.go

数据库连接优化
1. 简化数据库配置
2. 精简数据库连接代码

Db connect update

---

etc/server.conf

update server.conf, add DisableUsageReport

---

docker/initsql_for_postgres/a-n9e-for-Postgres.sql

pg数据库初始化脚本字段同步

---

docker/initsql_for_postgres/a-n9e-for-Postgres.sql

fix：pg数据库脚本同步

---

src/pkg/tplx/common.go
src/pkg/tplx/tplx.go

Feat：增加常用模板函数，提高与prometheus生态兼容性

Feat：增加常用模板函数

---

docker/initsql_for_postgres/a-n9e-for-Postgres.sql

fix: NotifyMaxNumber for postgres db

fix: NotifyMaxNumber for postgres db

---

src/server/router/router_prom.go

当数据是通过prometheus抓取（也许直接remote write到夜莺）的时候，prometheus会自动产生部分系统指标，例如最典型的有up指标，是prometheus为exporter自动生成的指标，即使exporter挂掉的时候也会送up=0的指标，此类指标在做ident nodata判断的时候应当剔除，否则会导致redis数据中时间戳被意外更新，例如在exporter宕掉的时候，会导致由此类指标中携带的ident的相关target_up指标无法变为实际的0值。
更多详细信息：https://prometheus.io/docs/concepts/jobs_instances/#automatically-generated-labels-and-time-series

Fix：fix target_up nodata judge for prometheus scrape

---

docker/initsql/a-n9e.sql
src/models/recording_rule.go
src/server/engine/worker.go

refactor recording rule and add field disabled

---

src/webapi/router/router.go

fix: fix event api for service

fix: fix event api for service

---

src/server/engine/mute.go
src/server/engine/worker.go

fix mute bug

---

src/webapi/prom/prom.go

fix get clusters by api

---

.github/workflows/n9e.yml
.goreleaser.yaml
docker/Dockerfile.goreleaser
fe.sh

feature , auto release with github action 
Feat #  auto release

auto release with github action

---

docker/initsql_for_postgres/a-n9e-for-Postgres.sql

fix: pg sql for recording rule

fix: pg sql for recording rule

---

Makefile

fix: fix version info

---

src/server/engine/mute.go
src/webapi/router/router_mw.go

Feature mute enhancement

---

src/models/alert_rule.go
src/models/common.go
src/models/recording_rule.go

[feat(#984)] multiple cluster support

---

src/models/alert_mute.go
src/models/alert_rule.go
src/models/alert_subscribe.go
src/models/common.go
src/models/recording_rule.go

mute & subscribe add multiple cluster support
fix mute AlertMuteGets query bug

[feature] support multiple cluster config with mute&subscribe

---

src/server/router/router_event.go

fix: event push api

---

src/models/alert_rule.go
src/server/router/router_event.go

fix get alert rules by api

---

etc/script/notify/notify.go
src/server/engine/notify.go
src/server/engine/notify_maintainer.go

supply plugin to notify maintainer

---

src/server/engine/mute.go
src/server/engine/worker.go
src/server/router/router_event.go

feat: push event api support mute

feat: push event api support mute

---

src/server/router/router_opentsdb.go

refactor: add error log

---

docker/docker-compose.yaml

docker compose use latest version of n9e and categraf

---

etc/script/rule_converter.py

支持将k8s中的rule-configmap、prometheus规则、vmalert规则转换为n9e中的alert/record规则

feat: support rule convert from prometheus/vmalert

---

etc/script/rule_converter.py
etc/template/README.md
src/pkg/tplx/tplx.go

1. 告警模版支持链接跳转到监控详情
2. 转换规则脚本添加样例配置

feat: support alert graph url

---

src/pkg/tls/config.go
src/webapi/config/config.go
src/webapi/prom/prom.go

feat: prom support tls

---

src/webapi/router/router.go

fix i18n header bug

---

etc/metrics.yaml
src/webapi/config/config.go
src/webapi/config/metrics.go
src/webapi/router/router_metric_desc.go

1. metric desc 支持i18n
2. metric desc 部分指标错误修复

feat: support i18n metric desc

---

etc/webapi.conf
src/models/target.go
src/webapi/router/router_target.go

1. 支持ident disk_used_percent根盘指标的采集

feat: support ident disk usage metric

---

src/server/engine/engine.go
src/server/engine/notify.go
src/server/server.go

support tpls reload

---

src/server/engine/engine.go
src/server/engine/notify_maintainer.go
src/server/engine/reporter.go
src/server/engine/worker.go
src/server/router/router.go
src/server/server.go

1. 优化nserver的错误通知方式，聚合一分钟内的错误再上报，避免海量错误消息

optimize error report

---

etc/metrics.yaml

增加 aws cloudwatch rds metrics 中文信息

---

src/server/engine/worker.go

线上遇到几次未触发告警问题，现有日志太少无法定位问题，增加了规则执行debug日志方便排查。

添加告警规则执行日志

---

README.md
doc/active-contributors.md
doc/committers.md
doc/community-governance.md
doc/contributors.md
doc/end-users.md
doc/pmc.md

improve community governance

---

src/models/alert_rule.go
src/server/engine/worker.go
src/server/router/router.go
src/server/router/router_event.go
src/webapi/router/router_alert_rule.go

feat: support handle event api

feat: support handle event service api

---

docker/initsql_for_postgres/a-n9e-for-Postgres.sql

docs: sync pg init sql

---

docker/initsql/a-n9e.sql
src/models/alert_cur_event.go
src/models/alert_his_event.go
src/models/alert_mute.go
src/models/alert_rule.go
src/models/alert_subscribe.go
src/server/config/config.go
src/server/engine/worker.go
src/server/router/router_event.go
src/webapi/router/router.go
src/webapi/router/router_alert_cur_event.go
src/webapi/router/router_alert_his_event.go
src/webapi/router/router_alert_rule.go

feat: alert rule support cate

---

src/models/busi_group.go

fix: add board check when del group

---

docker/initsql/a-n9e.sql

add id column for table user_group_member and role_operation

add id column for table user_group_member and role_operation

---

docker/n9eetc/server.conf
docker/n9eetc/webapi.conf
etc/server.conf
etc/template/mm.tpl
etc/webapi.conf
src/server/common/sender/dingtalk.go
src/server/common/sender/feishu.go
src/server/common/sender/mm.go
src/server/common/sender/wecom.go
src/server/engine/notify.go
src/server/engine/notify_maintainer.go

feature, add mattermost notification
Fixes #

add mattermost notification

---

src/models/alert_mute.go

fix: alert mute clean

---

docker/initsql/a-n9e.sql
docker/initsql_for_postgres/a-n9e-for-Postgres.sql
src/models/alert_subscribe.go
src/models/busi_group.go
src/server/engine/notify.go
src/webapi/router/router_alert_subscribe.go

feat: alert_subscribe add name and disabled

feat: alert_subscribe add name and disabled

---

docker/initsql_for_postgres/a-n9e-for-Postgres.sql

docs: fix pg init sql

---

src/models/configs.go
src/server/engine/worker.go
src/webapi/router/router.go
src/webapi/router/router_configs.go

feat: add configs service api

---

docker/initsql/a-n9e.sql
etc/webapi.conf
src/models/board.go
src/webapi/router/router.go
src/webapi/router/router_board.go
src/webapi/router/router_mw.go

/kind enhancement
We probably need to share the entire dashboard to other departments in the company, let them access anonymously.
Fixes #905
ddl for alter table:
```
alter table board add public tinyint(1) default 0 not null comment '0:false 1:true';
```

feat: support for sharing dashboards

---

src/webapi/prom/prom.go
src/webapi/router/router_prometheus.go

prom client support add header

---

go.mod
go.sum
src/main.go
src/pkg/secu/aes.go
src/server/config/config.go
src/server/server.go
src/webapi/config/config.go
src/webapi/router/router.go
src/webapi/router/router_crypto.go
src/webapi/webapi.go

feat: conf file password supports ciphertext
配置文件有明文密码会被安全扫描出漏洞，特提供一种基于AES加密方式的配置文件密文配置方式。
备注：
顺带更新了一下go-redis版本
Closes #1174

feat: conf file password supports ciphertext

---

docker/initsql_for_postgres/a-n9e-for-Postgres.sql

docs: pg init sql

---

src/models/alert_mute.go

bugfix:mute cannot be refreshed after being modified

alert mute cannot refresh the bug

---

src/server/memsto/log_sample_filter_cache.go
src/server/router/router.go
src/server/router/router_datadog.go
src/server/router/router_log_sample_filter.go
src/server/router/router_openfalcon.go
src/server/router/router_opentsdb.go
src/server/router/router_prom.go

feat: add timeseries sample log filter

feat: add timeseries sample log filter

---

etc/dashboards/mongo_by_exporter.json

mongodb 导入 dashboard模版后, 很多图表没有数据
Fixes #

update dashboard template for mongodb

---

etc/server.conf
etc/webapi.conf
src/storage/storage.go

fix: support redis sentinel password

---

etc/webapi.conf
src/pkg/oauth2x/oauth2x.go

support fetch user info based on query type

---

src/server/config/prom_option.go
src/server/config/reader.go
src/server/engine/worker.go
src/server/writer/writer.go

fix load prom options from database and add more log

fix load prom options from database and add more log 

---

src/server/engine/rule.go
src/server/naming/hashring.go
src/server/router/router.go
src/server/router/router_event.go

optimize handle external event

optimize handle external event

---

src/models/alert_cur_event.go

convert tplx.Funcmap  to text.funcmap

---

src/server/common/sender/dingtalk.go
src/server/common/sender/feishu.go
src/server/common/sender/mm.go
src/server/common/sender/redis_pub.go
src/server/common/sender/telegram.go
src/server/common/sender/wecom.go
src/server/engine/mute_strategy.go
src/server/engine/rule_alert.go
src/server/engine/subscription.go

subscribe code refactor

---

src/server/engine/rule.go
src/server/engine/rule_alert.go

1. 用hash作为external rulemap 存储的key
2. 修改externalRule的加锁粒度

engine code refactor

---

src/server/memsto/alert_mute_cache.go
src/server/memsto/alert_rule_cache.go
src/server/memsto/alert_subsribe_cache.go
src/server/memsto/recording_rule_cache.go
src/server/naming/heartbeat.go

optimize heartbeat and rule sync

optimize heartbeat and rule sync

---

src/server/config/prom_option.go
src/server/config/reader.go

fix: server query prom https api

---

src/models/alert_rule.go

compatible with alert rule older data structures

compatible with alert rule older data structures

---

docker/docker-compose.yaml

docs: prometheus image version
close #1363

docs: prometheus image version

---

alert/dispatch/consume.go
alert/dispatch/dispatch.go
alert/process/process.go
alert/sender/email.go
alert/sender/sender.go
center/cconf/conf.go
center/center.go
center/router/router.go
center/router/router_funcs.go
center/router/router_notify_config.go
center/router/router_task.go
etc/config.toml
memsto/notify_config.go

feat: smtp ibex config manage on the web page

feat: smtp ibex config manage on the web page

---

alert/eval/eval.go

fix nil pointer

---

pushgw/pconf/conf.go
pushgw/writer/writer.go

refactor: push series

---

center/router/router_datasource.go

add datasource check

---

integrations/elasticsearch/dashboards/elasticsearch_by_exporter.json
integrations/http/dashboards/http_response_by_categraf.json
integrations/jmx/dashboards/jmx_by_exporter.json
integrations/kafka/dashboards/kafka_by_exporter.json
integrations/linux/dashboards/linux_by_categraf.json
integrations/linux/dashboards/linux_by_exporter.json
integrations/linux/dashboards/linux_by_telegraf.json
integrations/mongo/dashboards/mongo_by_exporter.json
integrations/mysql/dashboards/mysql_by_categraf.json
integrations/mysql/dashboards/mysql_by_exporter.json
integrations/n9e/dashboards/n9e_server.json
integrations/net_response/dashboards/net_response_by_categraf.json
integrations/oracle/dashboards/oracle_by_categraf.json
integrations/ping/dashboards/ping_by_categraf.json
integrations/process/dashboards/process_by_exporter.json
integrations/rabbixmq/dashboards/rabbitmq_by_categraf.json
integrations/redis/dashboards/redis_by_categraf.json
integrations/redis/dashboards/redis_by_exporter.json
integrations/tomcat/dashboards/tomcat_by_categraf.json
integrations/vmware/dashboards/vmware_by_vsphere-monitor.json
integrations/windows/dashboards/windows_by_exporter.json
integrations/zookeeper/dashboards/zookeeper_by_exporter.json

change builtin board

---

docker/initsql_for_postgres/a-n9e-for-Postgres.sql
docker/initsql_for_postgres/b-ibex-for-Postgres.sql

docs: n9e and ibex init sql for postgresql

docs: n9e and ibex init sql for postgresql

---

integrations/linux/dashboards/linux_by_categraf.json

fix
bytesIED => bitsIEC
Fixes # 修复linux大盘中网络流量的单位

fix standard output option for dashboards

---

alert/sender/callback.go
docker/experience_pg_vm/initsql_for_postgres/a-n9e-for-Postgres.sql
docker/initsql/a-n9e.sql
models/task_record.go

feat: add eventid to ibex task_record
ibex自愈记录增加与告警事件ID的关联

feat: add eventid to ibex task_record

---

cli/upgrade/upgrade.sql
docker/experience_pg_vm/initsql_for_postgres/a-n9e-for-Postgres.sql
docker/initsql/a-n9e.sql
models/alerting_engine.go

compatible with TDSQL-C Mysql

---

cli/upgrade/upgrade.sql
docker/experience_pg_vm/initsql_for_postgres/a-n9e-for-Postgres.sql
docker/initsql/a-n9e.sql
models/alerting_engine.go

fix get engine cluster list

---

docker/Dockerfile.goreleaser
docker/Dockerfile.goreleaser.arm64

update dockerfile for github-action

---

docker/Dockerfile.goreleaser.arm64

chmod 755 wait for aarch64

---

.gitignore
docker/experience_pg_vm/initsql_for_postgres/a-n9e-for-Postgres.sql

docs: pg sql script and gitignore

docs: pg sql script and gitignore

---

docker/initsql/a-n9e.sql

MySQL8.0.20执行初始化SQL报错
定位报错语句：insert into busi_group_member(busi_group_id, user_group_id, perm_flag) values(1, 1, "rw");
报错信息：Unknown column 'rw' in 'field list'
原因分析："rw"使用了双引号

fix:Unknown column 'rw' in 'field list'

---

integrations/victoriametrics/dashboard/victoriametrics.json
integrations/victoriametrics/markdown/README.md

1. 修复vm为官方最新dashboard；
2. 调整dashboard中描述为中文；

fix vm old dashboard to new

---

center/router/router_datasource.go

fix: 修正添加loki 数据源校验问题

---

.goreleaser.yaml
Makefile
center/router/router.go
docker/Dockerfile
docker/Dockerfile.goreleaser
docker/Dockerfile.goreleaser.arm64
docker/build.sh
fe.sh
go.mod
go.sum

feat: embed front-end files into n9e executable
功能：利用https://github.com/rakyll/statik 项目 statik 将前端文件打包进n9e
1、前端文件以内存形式加载到http.FileSystem，速度比放磁盘上快很多
2、部署更为简单，只需要n9e，不需要/pub

feat: embed front-end files into n9e executable

---

models/alert_rule.go
models/target.go

fix: host filter

---

alert/router/router.go
center/router/router.go
conf/crypto.go
etc/config.toml
pkg/httpx/httpx.go
pushgw/router/router.go
pushgw/router/router_datadog.go

refactor basic auth configurations: merge HTTP.Pushgw and HTTP.Heartbeat to HTTP.APIForAgent; merge HTTP.Alert and HTTP.Service to HTTP.APIForService

refactor basic auth configurations

---

center/router/router.go
center/router/router_notify_tpl.go
models/notify_tpl.go

Provide notify template interface for creating&updating&deleting on the frontend page.
Add new interface of notifyTplAdd and notifyTplDel.
None.
Deleting system defaults is not supported.

Edit notify tpl

---

center/router/router.go
center/router/router_captcha.go
center/router/router_login.go
etc/config.toml
go.mod
go.sum
pkg/httpx/httpx.go
pkg/i18nx/const.go

feat: add verification code for login
增加登陆验证码（数学公式计算），解决安全扫描渗透测试中的暴力破解漏洞

feat: add verification code for login

---

integrations/ipmi/markdown/README.md

fix ipmi readme.md

---

pkg/i18nx/var.go

i18n const -> var

---

integrations/TiDB/alerts/tidb-alerts.json

update title of tidb alerts

---

alert/eval/eval.go
alert/mute/mute.go
alert/process/process.go
alert/record/prom_rule.go

refactor eval

---

alert/process/process.go

feat: mute hook

---

center/router/router.go
center/router/router_es_index_pattern.go
docker/initsql/a-n9e.sql
models/es_index_pattern.go

feat:index pattern format

---

center/router/router.go
center/router/router_es_index_pattern.go
docker/initsql/a-n9e.sql
models/es_index_pattern.go
models/migrate/migrate.go
models/migrate/migrate_es_index_pattern.go

index pattern basic op

---

integrations/Windows/dashboards/windows_by_categraf.json
integrations/Windows/markdown/README.md

fix windows dashboards label_values

---

docker/Dockerfile.goreleaser

install requests lib for python3

---

center/router/router.go
center/router/router_builtin.go
center/router/router_target.go
models/target.go
prom/client.go

support markdown api and downtime select

feat: support markdown api and downtime select

---

docker/experience_pg_vm/n9eetc_pg/config.toml

docs: fix docker-compose for pg-vm

docs: fix docker-compose for pg-vm

---

center/router/router.go
center/router/router_datasource.go

check datasource

---

alert/sender/callback.go
center/router/router.go
center/router/router_task_tpl.go
models/task_tpl.go

fix: n9e edge get tpl

---

center/center.go

注册cstats的指标，获取接口访问的次数和持续时间
Fixes #1652 

fix: open cstats init

---

pkg/poster/post.go

fix: post err process

---

center/router/router_proxy.go

refactor: proxy api

---

alert/common/key.go
alert/dispatch/dispatch.go
center/router/router_alert_subscribe.go
models/alert_mute.go
models/alert_subscribe.go
models/migrate/migrate.go

add BusiGroupFilter for alert_subscribe ,copy from TagFiler
alert_subscribe can filter with busigroup name(like TagFilter)
None

Add BusiGroupFilter for alert_subscribe ,copy from TagFilter

---

storage/redis.go

use redis.Cmdable instead of Redis

---

center/router/router_login.go
pkg/cas/cas.go
pkg/oauth2x/oauth2x.go
pkg/oidcx/oidc.go

feat: sso support skip tls verify

---

models/migrate/migrate.go

Automatically migrate recent table structure changes. 
Utilize a migration tool to apply recent table structure changes.
None. 
None.

fix: Automatically migrate recent table structure changes. 

---

pkg/prom/reader.go

remove  invalid code

---

integrations/HTTP/alerts/http_response_by_categraf.json

Add a alert rule about https certificate.
Help us with certificate monitoring.
None
None

Update a alert rule about https certificate

---

center/router/router.go
center/router/router_configs.go

config api

---

pkg/i18nx/i18n.go

Feat: merge i18n configuration
Merge expand config and build-in, prioritize the settings within the expand config options in case of conflicts
None

feat: merge i18n configuration

---

pkg/httpx/httpx.go
pkg/secu/rsa.go

Fix: Optimize user config
If the RSAPrivateKeyPath file does not exist, automatically generate an RSA key.
None.

fix: Optimize user config

---

models/datasource.go
models/migrate/migrate.go

Datasource add is_default column

---

center/cconf/ops.go
center/center.go
center/router/router_builtin.go
etc/ops.yaml
models/migrate/migrate.go
pkg/i18nx/i18n.go

feat: merge operation permission points from built-in
Merge operation permission points and give priority to the settings within the 'ops.yaml' file options in case of conflicts(`ops.name`)
Nnoe.

feat: merge operation permission points from built-in

---

center/router/router_task.go
models/task_tpl.go

perf: convert task script line endings

---

pkg/secu/rsa.go

fix:  rsa  decrypt & generate method
Maintain consistency between encryption and decryption methods.
None.

fix: rsa decrypt & generate method

---

center/router/router.go
center/router/router_heartbeat.go
models/host_meta.go
models/target.go

refactor: heartbeat api

---

center/router/router_notify_config.go
memsto/notify_config.go
pkg/tplx/tplx.go

fix: add func for tplx, avoid escape issues caused by special characters
add func for tplx, avoid escape issues caused by special characters

fix: add func for tplx, avoid escape issues caused by special characters

---

center/router/router_notify_config.go
memsto/notify_config.go
pkg/tplx/tplx.go

Fix: use text template to replace data
use text template to replace data

Fix:use text template to replace data

---

center/router/router_proxy.go
pkg/aop/log.go
pkg/httpx/httpx.go

feat: http support print body log

---

integrations/Windows/dashboards/windows_by_categraf.json

fix: fix windows dashboard

---

models/alert_rule.go

feat: host filter support *

---

alert/alert.go
center/center.go
cmd/edge/edge.go
models/alert_cur_event.go
prom/client.go
prom/reader.go
pushgw/router/fns.go
pushgw/router/router.go

refactor:  timeteries handle hook

refactor:  timeteries handle hook

---

pkg/prom/writer.go
pushgw/writer/writer.go

feat: writer support mult addrs

feat: writer support mult addrs

---

docker/initsql/migrate.sql
models/migrate/migrate.go
models/target.go

target add agent version

---

alert/sender/dingtalk.go
alert/sender/email.go
alert/sender/feishu.go
alert/sender/feishucard.go
alert/sender/mm.go
alert/sender/sender.go
alert/sender/telegram.go
alert/sender/wecom.go
center/router/router.go
center/router/router_notify_tpl.go
models/migrate/migrate.go
models/notify_tpl.go

refactor build noitfy tpl

---

integrations/Canal/dashboards/canal_by_categraf.json

update dashboards
update dashboards

fix: dashboards of canal

---

center/cconf/ops.go
center/router/router_target.go
models/target.go

add /targets/bind perm & fix panic

---

memsto/config_cache.go

What type of PR is this?
This PR is a "Bug Fix"
What this PR does / why we need it:
cause error message loss and while err == nil &  decryptErr != nil the program will panic
Which issue(s) this PR fixes:
Fixes # (Please provide an actual issue number or issue link if this PR is associated with a specific issue)
Special notes for your reviewer:
This PR's changes are crucial as they address a potential error and exception scenario. Please pay special attention to the variable name changes to ensure they are correctly updated and utilized in the code. Additionally, help ensure that the changes introduced do not lead to new issues or side effects in the code. Thank you for your review!

Fix error variable incorrect invocation

---

integrations/Oracle/alerts/oracle_alert.json

docs: add oracle alert rule template

---

pkg/oidcx/oidc.go

refactor: optimize oidc get user info

refactor: optimize oidc get user info

---

alert/process/process.go

fix: build event

---

center/router/router.go
center/router/router_alert_rule.go
center/router/router_board.go
center/router/router_target.go
models/alert_rule.go
models/board.go
models/board_busi.go
models/migrate/migrate.go
models/user_group_member.go

refactor: share board 

---

alert/process/process.go
pushgw/router/router_remotewrite.go

fix: extractIdentFromTimeSeries append labels

fix: extractIdentFromTimeSeries append labels

---

alert/alert.go
alert/eval/alert_rule.go
alert/eval/eval.go
alert/naming/hashring.go
alert/naming/heartbeat.go
alert/process/process.go
alert/record/scheduler.go
alert/router/router_event.go
center/center.go
center/metas/metas.go
center/router/router.go
center/router/router_heartbeat.go
center/router/router_server.go
center/router/router_target.go
cmd/edge/edge.go
docker/initsql/migrate.sql
memsto/host_alert_rule_targets.go
memsto/target_cache.go
memsto/targets_of_alert_rules.go
models/alert_rule.go
models/host_meta.go
models/migrate/migrate.go
models/target.go
pushgw/idents/idents.go
pushgw/idents/update_ts.go
pushgw/pushgw.go
pushgw/router/router.go
pushgw/router/router_heartbeat.go
pushgw/router/router_target.go

refactor:host alert in edge

---

alert/naming/hashring.go
center/cconf/conf.go
center/center.go
center/router/router_funcs.go
center/router/router_user_group.go
memsto/user_cache.go
models/configs.go
pkg/flashduty/post.go
pkg/flashduty/sync_user.go
pkg/flashduty/sync_user_group.go

feat: sync user and user_group to flashduty

---

go.mod
go.sum
memsto/drop_ident.go
pushgw/pconf/conf.go
pushgw/router/fns.go
pushgw/router/ident_stats.go

feat: auto drop metrics by ident threshold

feat: auto drop metrics by ident threshold

---

center/router/router_user_group.go
memsto/user_cache.go
pkg/flashduty/post.go
pkg/flashduty/sync_user.go
pkg/flashduty/sync_user_group.go

refactor: optimize sync user to duty

refactor: optimize sync user to duty

---

center/sso/init.go

sso template format unified 

---

alert/eval/eval.go
alert/process/process.go

fix: handle host recovery event

fix: handle host recovery event

---

alert/eval/eval.go
alert/process/process.go

refactor: handle event

---

integrations/SQLServer/collect/sqlserver.toml

sync sqlserver config from categraf

sync sqlserver config

---

integrations/IPMI/dashboards/IPMI_by_categraf.json

Add a new IPMI dashboard for version v0.3.44-pre and subsequent versions.

Add a new IPMI dashboard

---

docker/compose-postgres/categraf/conf/config.toml

docs: fix pg docker config

---

alert/alert.go
alert/sender/email.go

fix: Rebooting the email sender through cache

fix: sync smtp config

---

integrations/SpringBoot/dashboards/JVM(Actuator)2.0.json
integrations/SpringBoot/dashboards/JVM(Actuator)withapplicationname.json

update dashboard for springboot 
dashboard for springboot
Fixes # dashboard for v6 or later version needs configure datasource

update dashboards for springboot

---

alert/process/process.go

fix: typo error

---

center/router/router_self.go
center/router/router_user.go

Encrypted password
Transmitting password by encrypting using the RSA algorithm.

Feat: encrypted password

---

center/router/router_mute.go

chore: fix function name in comment

---

integrations/IPMI/dashboards/IPMI.json

chore: update dashboards for ipmi

---

alert/sender/email.go
go.sum
models/user.go

1. In the user management interface, business group and team information have been added
2. fixes an SMTP configuration error in the mail alert system.
1. This PR enhances the existing user querying functionality by incorporating the ability to fetch and display associated user groups and business groups, reflecting the many-to-many relationships in the data model. These enhancements are necessary to provide a comprehensive view of user affiliations and permissions in the user interface, which are crucial for administrative and audit purposes in the application.
2. Resolved issue with infinite retries due to misconfiguration, and resulting frequent error logging.
In addition, it also solves the problem of being unable to …

Add fields to the users interface and fix email sending bugs

---

center/center.go
center/sso/init.go
memsto/config_cache.go

Add user variable for sso(decrypted).

feat: add user variable for sso(decrypted).

---

models/task_tpl.go
pkg/i18nx/var.go

Fixes #
In actual use, some tasks require more than 1 day to complete, so I hope to extend the time limit appropriately to provide more options.

Change the task time limit from 1 day to 5 days.

---

center/router/router.go
center/router/router_target.go
models/target.go
models/user.go

Optimize
This PR introduces the following improvements:
1. **target** API adjustments to include the result of each machine in the `failure_reasons` field.
2. Adds a new **service** interface.
3. Supports operations on **target** based on IP addresses.
These changes are essential to enhance the flexibility and functionality of the existing APIs, allowing more versatile and comprehensive management of targets using both `ident` and `host_ip`.
- Ensures backward compatibility while extending the functionality.
- Comprehensive error handling and validation for the new IP-based operations.

optimize: Optimize targets-related interfaces

---

center/router/router_mw.go
memsto/user_cache.go
models/migrate/migrate.go
models/user.go

- feature
This PR adds a new field `LastActiveTime` to the `User` model and implements a mechanism to periodically update this field in the database. This helps track user activity more accurately and improves data consistency.
Please review the `UserCacheType` implementation, especially the new methods for updating `LastActiveTime`. Ensure that the periodic update logic does not introduce any performance issues or race conditions.

optimize: add user last active time

---

center/router/router_user.go
models/user.go

This is a feature enhancement.
This PR adds support for sorting users based on specified fields and allows filtering based on a time range (stime and etime). This enhancement improves the flexibility of user queries, making it easier to organize and analyze user data.

optimize: add order and betwen query

---

integrations/ClickHouse/alerts/clickhouse_by_categraf.json
integrations/ClickHouse/alerts/clickhouse_by_exporter.json
integrations/ClickHouse/dashboards/clickhouse_by_categraf.json
integrations/ClickHouse/dashboards/clickhouse_by_exporter.json
integrations/ClickHouse/metrics/clickhouse_by_categraf.json
integrations/ClickHouse/metrics/clickhouse_by_exporter.json

clickhouse:alerts,dashboards,metrics

clickhouse:alerts,dashboards,metrics

---

alert/sender/feishucard.go

Fixes
Fixes # 
修复 feishucard  无法 at 人的问题.  增加了可以使用 email 进行 at  

fix feishucard ats

---

center/router/router_login.go
pkg/cas/cas.go
pkg/oauth2x/oauth2x.go

sso_login_defaultGroups:cas,oauth2

---

alert/sender/webhook.go

Bug Fix
Skip verify ssl doesn't work [#2028](https://github.com/ccfos/nightingale/issues/2028)
Fixes  [#2028](https://github.com/ccfos/nightingale/issues/2028)
@710leo

Feat: Add skip Verify Insecure ssl/tls in sendWebhook

---

center/router/router_target.go
models/target.go

refactor: targets get api support backend sorting

---

alert/dispatch/dispatch.go
alert/sender/callback.go
alert/sender/lark.go
alert/sender/sender.go
center/router/router_notify_config.go
models/notify_tpl.go
models/user.go

Noti chan add lark

---

alert/dispatch/dispatch.go
alert/sender/callback.go
alert/sender/plugin.go
alert/sender/webhook.go
center/router/router_notification_record.go
models/notification_record.go
models/user.go

1. Add notification records for plugin and webhook
2. Optimize the construction logic of noti list
Fixes #

record alert noti

---

alert/dispatch/dispatch.go
alert/sender/ibex.go
center/router/router_task_tpl.go
models/alert_rule.go
models/migrate/migrate.go

alert rule add task tpl

---

center/router/router_heartbeat.go
models/migrate/migrate.go
models/target.go

target add os type

---

center/router/router_alert_rule.go
models/alert_rule.go

batch update annotation

---

center/integration/init.go
center/router/router_builtin_componet.go
center/router/router_builtin_payload.go
models/builtin_component.go
models/builtin_metrics.go
models/builtin_payload.go
models/migrate/migrate.go

1. 改变了 builtin_payloads 与 builtin_components 的外键关联，原本使用 component_ident 现在使用 component_id
2. builtin_components 修改时开启事物修改 builtin_metrics
3. 不允许修改 system 创建的 builtin_components

fix-tpl-update

---

center/router/router.go
center/router/router_alert_rule.go
models/alert_rule.go
models/prom_alert_rule.go
models/prom_alert_rule_test.go

import promethues alert rule

---

models/alert_cur_event.go

clean up
1. DB2FE, when json unmarshal error need return err not nil
2. update recive name to same
Fixes #

Fix json err

---

center/router/router_heartbeat.go
center/router/router_target.go
models/migrate/migrate.go
models/target.go

update target tags

---

center/router/router.go
center/router/router_alert_rule.go
go.mod
go.sum
models/alert_rule.go

1. 提供克隆规则到不同机器的接口
2. 批量更新接口新增批量更新告警条件

Clone rule and batch update rule

---

README.md
README_en.md

- add language switch introduction
- refine english readme
Fixes #

refine english readme

---

models/alert_rule.go
models/target.go

fix: add host tags

---

alert/eval/eval.go
alert/eval/eval_test.go
center/center.go
models/alert_rule.go
pkg/hash/hash.go

1. 将各个查询记录的 hash 值分开存放，便于后续实现集合操作
2. 支持多个查询（集合）指定联合字段的内联操作

trigger set operation supporting on

---

alert/eval/eval.go
alert/mute/mute.go
alert/sender/ibex.go
center/center.go
center/router/router.go
center/router/router_heartbeat.go
center/router/router_target.go
memsto/target_cache.go
models/migrate/migrate.go
models/target.go
models/target_busi_group.go
models/user.go
pushgw/pconf/conf.go
pushgw/router/fns.go

host set multi busi group

---

alert/process/process.go
models/alert_cur_event.go

put target into alert cur event

---

center/router/router_funcs.go
center/router/router_target.go
models/target.go

targets support multi idents query

---

center/router/router.go
center/router/router_target.go
models/target.go

target delete hook

---

center/router/router_alert_cur_event.go
center/router/router_alert_his_event.go
center/router/router_alert_rule.go
models/alert_cur_event.go
models/alert_his_event.go
models/alert_rule.go

Query alert event by rule id

---

alert/eval/eval.go
alert/mute/mute.go
alert/sender/ibex.go
center/cconf/conf.go
center/center.go
center/router/router.go
center/router/router_heartbeat.go
center/router/router_target.go
memsto/target_cache.go
models/migrate/migrate.go
models/target.go
models/target_busi_group.go
models/user.go
pushgw/pconf/conf.go
pushgw/router/fns.go

host set multi group

---

alert/dispatch/dispatch.go
alert/dispatch/notify_target.go
alert/sender/webhook.go

alert rule callback url dedup

---

alert/dispatch/notify_target.go

Bug fix
Fix slice init length 
Fixes #

bug: fix slice init length

---

center/router/router.go
center/router/router_builtin_payload.go

新增根据 uuid or id 查询 builtin-payloads 的接口

get build payload by uuid

---

models/alert_rule.go
models/target.go
models/user.go

fix: host set muti group

---

center/router/router_alert_cur_event.go
center/router/router_alert_his_event.go
center/router/router_alert_rule.go
models/alert_cur_event.go
models/alert_his_event.go
models/alert_rule.go

Query alert event by rule

---

alert/eval/eval.go
alert/mute/mute.go
alert/sender/ibex.go
center/cconf/conf.go
center/center.go
center/router/router.go
center/router/router_heartbeat.go
center/router/router_target.go
memsto/target_cache.go
models/alert_rule.go
models/migrate/migrate.go
models/target.go
models/target_busi_group.go
models/user.go
pushgw/pconf/conf.go
pushgw/router/fns.go

host set muti group

---

pkg/ldapx/ldapx.go
pkg/ldapx/user_sync.go

multi ldap dn

---

center/router/router_datasource.go
models/datasource.go

datasouce support force save

---

center/router/router_alert_rule.go
models/alert_rule.go
models/user.go

rule list use user display name

---

pkg/oauth2x/oauth2x.go

Optimize oauth2

---

alert/alert.go
center/center.go
center/router/router_funcs.go
cmd/edge/edge.go
memsto/config_cval_cache.go
models/configs.go
pkg/aop/log.go
pkg/httpx/httpx.go
pushgw/pushgw.go

Reverts ccfos/nightingale#2181

Revert "Revert "support to config access log""

---

models/target.go

fix: unbind bgids when delete target

---

alert/common/conv.go
alert/eval/eval.go
alert/process/process.go
models/alert_cur_event.go
models/alert_rule.go

Alert recover

---

alert/eval/eval.go
alert/process/process.go
alert/router/router_event.go

调用 RecoverSingle 函数时指明是否由 recoverPoint 产生

hotfix: distinguish point

---

pkg/logx/logx.go

output logs to one file only

---

pushgw/writer/relabel.go

修复 relabel 时 replace 传入空值导致标签展示错误

fix relabel

---

models/alert_cur_event.go

add ExtraInfoMap in alert event

---

alert/process/process.go
memsto/busi_group_cache.go
models/target.go

fill group names in target

---

alert/sender/callback.go
alert/sender/dingtalk.go
alert/sender/email.go
alert/sender/feishu.go
alert/sender/lark.go
alert/sender/larkcard.go
alert/sender/mm.go
alert/sender/telegram.go
alert/sender/wecom.go

record noti for callback

---

center/router/router_datasource.go
center/router/router_proxy.go
models/alert_rule.go
models/datasource.go

es support set urls

---

models/prom_alert_rule.go

improve prom rule name

---

center/center.go
models/target.go

migrate network device busi group label

---

integrations/Oracle/collect/oracle/oracle.toml

docs: add metrics config for oracle

---

alert/eval/eval.go
alert/eval/eval_test.go
models/alert_rule.go

var for rule

---

center/router/router_notify_tpl.go

fix: notify tpl add miss creator

---

alert/astats/stats.go
alert/dispatch/consume.go
alert/eval/eval.go
alert/process/process.go
memsto/busi_group_cache.go

自监控指标 CounterRuleEvalErrorTotal 添加 
业务组名称标签 busigroup_name
告警规则 id 标签 rule_id

refactor-self-metric

---

center/center.go
models/user.go

feat: add console log with n9e address and root username/passwd when init root

feat: add console log with n9e address and root username/passwd when init root

---

alert/eval/eval.go
models/alert_rule.go
models/migrate/migrate.go

cron for alert rule

---

models/user.go

fix: get busi-groups api err

---

center/router/router.go
center/router/router_busi_group.go
center/router/router_heartbeat.go
center/router/router_target.go
models/target.go
models/target_busi_group.go

improve target bind bg logic

---

alert/eval/eval.go
alert/process/process.go
models/alert_cur_event.go
models/alert_rule.go

fix: alert rule cron eval

---

models/alert_rule.go
models/target.go

fix targets filter logic

---

alert/eval/eval.go
alert/eval/eval_test.go

当 promql 中包含聚合函数时原变量逻辑不生效，新增对该类 promql 对处理逻辑

var support for aggregate function

---

alert/eval/eval.go
alert/eval/eval_test.go

fix: quotation mark for alert rule var

---

models/migrate/migrate.go
models/migrate/migrate_test.go

fix: fix role_operation abnormal count

fix: fix role_operation abnormal count

---

models/busi_group.go

feat: add pre check for deleting busi_group

feat: add pre check for deleting busi_group

---

etc/config.toml
pushgw/pconf/conf.go
pushgw/writer/writer.go
pushgw/writer/writer_test.go

feat: add global metric write rate control

feat: add global metric write rate control

---

models/configs.go

add id for configsGetAll

---

center/router/router_tdengine.go

super table

---

models/busi_group.go

group delete check

---

center/router/router.go
center/router/router_query.go
datasource/tdengine/tdengine.go
dscache/sync.go

Hotfix td table

---

center/router/router_target.go

fix the dedup logic when adding tags to target

---

center/router/router_mw.go

refactor get user from context

---

center/router/router_target.go

feat: update target update group part

---

alert/eval/alert_rule.go
models/alert_rule.go

ck and es for alert rule

---

alert/alert.go
alert/eval/alert_rule.go
alert/eval/eval.go
center/router/router_target.go
memsto/host_alert_rule_targets.go
memsto/target_cache.go
models/alert_rule.go
models/target.go

optimize host query

---

center/router/router_builtin_componet.go
docker/compose-postgres/initsql_for_postgres/a-n9e-for-Postgres.sql
docker/initsql/a-n9e.sql
docker/migratesql/migrate.sql
models/builtin_component.go
models/builtin_payload.go

support setting builtin component to disabled

---

integrations/CloudWatch/collect/cloudwatch/cloud.toml
integrations/CloudWatch/markdown/README.md

update collections and readme for cloudwatch
Fixes #

chore: update tpl and readme for cloudwatch

---

integrations/CloudWatch/collect/cloudwatch/cloud.toml

chore: default interval for cloudwatch collecting

---

alert/dispatch/dispatch.go
memsto/notify_config.go

notify channel mute

---

etc/config.toml
pushgw/kafka/producer.go
pushgw/pconf/conf.go
pushgw/writer/kafka_writer.go
pushgw/writer/relabel.go
pushgw/writer/stats.go
pushgw/writer/writer.go

pushgw transfer time series data to kafka

---

alert/alert.go
center/cconf/ops.go
center/router/router.go
center/router/router_message_template.go
center/router/router_notify_channel.go
center/router/router_notify_rule.go
models/message_tpl.go
models/migrate/migrate.go
models/notify_channel.go
models/notify_rule.go
pkg/i18nx/var.go
pkg/slice/contains.go
pkg/str/verify.go

crud for message template, notify rule and notify channel

---

alert/sender/plugin.go

feat: support recording script alert results

---

alert/alert.go
alert/astats/stats.go
alert/sender/callback.go
alert/sender/notify_record_queue.go
center/router/router_notification_record.go

refactor: async alert notification record

---

alert/dispatch/dispatch.go
alert/sender/callback.go
alert/sender/email.go
alert/sender/mm.go
alert/sender/plugin.go
alert/sender/telegram.go
alert/sender/webhook.go
memsto/notify_channel_cache.go
models/notification_record.go
models/notify_channel.go
models/notify_channel_test.go

notify record and concurrency control for http

---

alert/dispatch/dispatch.go
center/router/router.go
center/router/router_notify_rule.go
models/alert_his_event.go
models/message_tpl.go
models/notify_channel.go

notify mute and test api

---

alert/alert.go
alert/astats/stats.go
alert/dispatch/consume.go
alert/dispatch/event_retry_consume.go
center/center.go
cmd/edge/edge.go

在 edge 发送 event 到 center 时，如果失败，会存储到队列中，循环尝试发送到center

Retry send event if fail send to center

---

dskit/sqlbase/timeseries.go
integrations/CloudWatch/markdown/README.md
pkg/osx/osx.go

Docs update
fix some comments
Fixes #

chore: fix some comments

---

alert/sender/sender.go
models/message_tpl.go
models/notify_channel.go
models/user.go

feature: Notified discord

---

center/router/router.go
center/router/router_alert_rule.go
models/alert_rule.go

feat: allow clone alert rules

---

memsto/config_cache.go

bugfix
fix call errors.WithMessage with a nil value error `err`, this should use `decryptErr`
Fixes #

fix call errors.WithMessage with a nil value error err

---

alert/mute/mute.go
models/alert_mute.go

在调用 alert-mute 接口时，添加 avtivated 返回值，表示当前告警屏蔽是否被激活

feat: return value add "avtivate" when get alert-mute

---

models/configs.go

feat: 支持 flashduty_app_key 加密配置项的自动解密处理

feat: support decrypting flashduty_app_key

---

center/router/router_user.go
models/user.go

为 /users 接口添加 通过email、phone搜索功能，可支持多个email或phone，通过 ',' 分隔

feat: support user get by email and phone

---

pkg/flashduty/sync_user_group.go

Fix: Fixed the issue of group synchronization flashduty

---

alert/record/prom_rule.go

fix :Record rule name change is not synchronized

---

center/cconf/ops.go
center/center.go
center/router/router.go
center/router/router_embedded.go
docker/initsql/a-n9e.sql
models/EmbeddedProduct.go
models/embedded_product.go
models/migrate/migrate.go
pkg/i18nx/var.go
pkg/ormx/database_init.go
pkg/ormx/ormx.go

feat: support update embedded-product

---

center/router/router.go
center/router/router_alert_cur_event.go
docker/compose-postgres/initsql_for_postgres/a-n9e-for-Postgres.sql
docker/initsql/a-n9e.sql
docker/sqlite.sql
models/alert_aggr_view.go
models/alert_cur_event.go
models/datasource.go
models/migrate/migrate.go
pkg/ormx/database_init.go

feat ： Supports my_group and format parameters

---

pushgw/writer/json/json-iterator.go
pushgw/writer/writer.go

Use jsoniter json to fix the problem that prom does not parse json

fix: Solved the problem of NaN value of prom not parsing json

---

models/notify_channel.go

N9e panic when gomail connection is failed.
Fixes #

fix: panic when gomail dial tcp failed.

---

center/router/router_alert_cur_event.go
models/alert_cur_event.go

feat : add event_Ids to alert-cur-events/list 

---

models/message_tpl.go
models/notify_channel.go

fix: telegram notify channel template

---

center/router/router.go
center/router/router_alert_his_event.go
models/alert_his_event.go

feat: alert history events delete function

---

models/user_token.go

fixed：compatible user_token table with postgresql

---

dskit/clickhouse/clickhouse.go
dskit/doris/doris.go
dskit/sqlbase/base.go
dskit/tdengine/tdengine.go

for slice, when marshal, return [] instead null
