ccfos/nightingale

- etc/collector.yml
ifconfig 和 route 命令，写绝对路径会导致兼容性不好。
1. Debian系统路径对应： /sbin/ifconfig 和 /sbin/route
2. 原命令获取的IP地址兼容性不好，会带“addr:”在前面。 addr:192.163.10.31
3. 本地配置正确的情况下 `hostname -i`是能拿到正确IP的
> 更新IP地址的获取方式

- src/modules/collector/config/config.go
- src/modules/index/config/config.go
- src/modules/monapi/config/yaml.go
- src/modules/tsdb/config/config.go
The sync.RWMutex cannot work as you expect as a result of you return the pointer directly.
In these scenarios that don't need to update your configurations regularly, the lock is useless, so delete it.
> delete useless lock

- src/toolkits/address/address.go
monapi:
http: '[::]:5800'
address:
- '[::1]'
transfer:
http: '[::]:5810'
rpc: '[::]:5811'
address:
- '[::1]'
> 修改adress.go的convPort方法，支持IPv6地址之间建立连接。

- src/modules/monapi/scache/init.go
- src/modules/transfer/cron/stra.go
**1. 修复与条件策略生成俩次告警事件的bug**:
**2. 排除节点排除选中节点下所有叶子节点**:
> [transfer] fix and trigger generates event twice bug

- src/modules/index/cache/metric_map.go
> 修复metricIndex的TagkvMap初始化两次造成的内存浪费

- dockerfiles/n9e/Dockerfile
优化Dockerfile
1.  执行 bash 脚本之前最好加上 `set -ex`，因为脚本执行过程中可能会出错，`-e` 在出错时会立即退出， `-x` 会打印出错误调用栈
[GNU手册](https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html)
2.  用包管理工具安装软件之后应清理缓存，可以减小镜像体积，[Docker文档](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run)   In addition, when you clean up the apt cache by removing /var/lib/apt/lists it reduces the image size, since the apt cache is not stored in a layer. ，[参考](https://stackoverflow.com/questions/46089219/how-to-reduce-the-size-of-rhel-centos-fedora-docker-image)
Fixes #
> clean cache, reduce image size

- src/models/mon_event.go
- src/modules/monapi/alarm/event_consumer.go
优化告警收敛查询数据库中告警事件统计
[FIX][issue#433]优化告警收敛，查询告警事件统计数据数据时使用created做between查询数据库时耗时非常久的问题，修改为使用etime 可以命中etime索引，提升查询性能，4C8G查询100W告警事件大概9s耗时，修改为etime大概700ms耗时
Fixes # https://github.com/didi/nightingale/issues/433
**Special notes for your reviewer**: @UlricQin @710leo
> [FIX][issue#433]优化告警收敛，查询告警事件统计数据数据时使用created做between查询数据库时耗时非常久的问题，修改为使用etime 可以命中etime索引，提升查询性能，4C8G查询100W告警事件大概9s耗时，修改为etime大概700ms耗时

- etc/sms.tpl
- src/modules/monapi/notify/notify.go
BUGFIX:
报警说明里的信息由于 html template 的转义，会将部分字符转义为 html 表示，但是短信内容不需要转义。
向 template 模板添加 unescaped 处理函数，并在模板文件中使用 unescaped 标识不需要转义的字段，实现避免转义
> BUGFIX: 修复短信报警模板的转义问题

- src/models/user.go
Signed-off-by: ysicing <i@ysicing.me>
Fixes #453
> fix: ldap登录如果配置允许coverAttributes，会导致panic

- src/modules/agent/agent.go
- src/modules/agent/core/clients.go
- src/modules/agent/sys/funcs/fsstat.go
探测使用的文件名添加随机字符串后缀，防止使用共享存储的多个机器文件名冲突
顺手改了下 rpcClients 的初始化，使用 init 函数初始化
> MOD: agent 文件系统 rw 探测

- src/modules/rdb/cron/sender_im.go
- src/modules/rdb/dingtalk/dingtalk.go
如果是采取钉钉告警的话，钉钉告警只能通过群聊发送，如果不支持at 别人，人一多容易出现消息没人理的情况。
将特定人员配置为告警接收人，同时对应将个人配置中电话号码填写在IM字段里面，即可在告警时at特定的人。
实现：
增加了dingding机器人at 员工的struct，同时在遍历接受告警人的同时，进行正则匹配，如果匹配到手机号码就append到atUser
> 钉钉告警可以at特定指定人员

- dockerfiles/n9e/Dockerfile
What type of PR is this?
这是什么类型的PR？
*  fix golang build fail in Dockerfile
修复了在Dockerfile里面go程序 build 失败问题（阿里云镜像的资源404导致build失败，改成直连资源后解决）
> fix golang build fail in Dockerfile

- src/modules/agent/http/router.go
- src/modules/agent/http/router_endpoint.go
add a method to get the Endpoint
addr: http://agent_host:port/v1/endpoint
增加了一个方法让客户端可以获得endpoint
接口地址：http://agent_host:port/v1/endpoint
> add a method to get the Endpoint【增加客户端获取Endpoint的方法】

- src/modules/monapi/plugins/all/dlopen.go
> use logger.Warning instead of fmt.Printf at loading plugins

- etc/plugins/prometheus.yml
- src/modules/prober/manager/accumulator/accumulator.go
已有 summary 指标生成的函数，仅操作生效
添加 promethues 配置文件，使 prober 上报生效
> MOD: 生效 prober promethues 监控的 summary 指标

- control
improve and bugfix
1. 提升运行control命令体验，用户经常会习惯使用tab来键入要操作的模块文件名
2. 修复exec函数中mod变量错误
> perf: control command support mod name with n9e- prefix

- etc/agentd.yml
perf
目前计算内存和硬盘的时候，直接取整数部分偏差较大，如4G内存，得到Gi为3.7Gi，但目前只显示3Gi差得太多
> perf: mem and disk size calc from %d to %.1f

- src/modules/agentd/sys/plugins/scheduler.go
**优化用户配置环境变量的情况下插件依赖系统环境变量问题**
现象描述： 这个插件是一个执行ss 命令的脚本， 如果不配环境变量则正常执行， 如果随便配置一个环境变量，则找不到ss命令了 
```tex
func PluginRun(plugin *Plugin) {
.....
if plugin.Env != "" {
envs := make(map[string]string)
err := json.Unmarshal([]byte(plugin.Env), &envs)
if err != nil {
logger.Errorf("plugin:%+v %v", plugin, err)
return
}  
for k, v := range envs {
cmd.Env = append(cmd.Env, fmt.Sprintf("%s=%s", k, v))
}
}
err := cmd.Start()
if err != nil {
logger.Error(err)
return
}
....
}
func (c *Cmd) Start() error {
......
envv, err := c.envv()
if err != nil {
return err
}
......
}   
func (c *Cmd) envv() ([]string, error) {
if c.Env != nil {
return c.Env, nil
}
return execenv.Default(c.SysProcAttr)
}
```
原因：从源码来看这里的环境变量并没有把系统环境变量（或者说当前进程的环境变量）带上
​           1.不在界面配置环境变量的情况，exec包里会用默认系统环境变量（或者说当前进程的环境变量），所以不会有问题 …
>  add system env when plugin run

- sql/n9e_mon.sql
- sql/upgrade/n9e_mon-v4.0.4.sql
- src/models/mon_event_cur.go
- src/models/node.go
- src/modules/server/alarm/event_reader.go
- src/modules/server/cache/init.go
- src/modules/server/cache/monapi_event_cur.go
- src/modules/server/cache/node.go
- src/modules/server/cache/node_idents.go
- src/modules/server/judge/judge.go
- src/modules/server/redisc/funcs.go
1.修复因重启n9e-server导致LastEvent丢失，新上报数据未触发告警，导致无法发送告警恢复问题；2.并发处理event_reader,增强告警处理性能
> 1.修复因重启n9e-server导致LastEvent丢失，无法发送告警恢复问题；2.并发处理event_reader,增强告警处理性能

- etc/identity.yml
修复 agent 所在系统有多个网卡启动失败问题
修复问题
修复 agent 启动失败问题。
Fixes #
当系统内有多个网卡，`route` 命令可能会获取到多个默认路由：
```
[root@xxx etc]# route|grep '^default'
default         gateway         0.0.0.0         UG    100    0        0 eth0
default         gateway         0.0.0.0         UG    101    0        0 eth1
```
此时会导致命令执行失败：
```
[root@xxx etc]# route|grep '^default'|awk '{print $NF}'
eth0
eth1
[root@xxxetc]# ifconfig `route|grep '^default'|awk '{print $NF}'`
eth1: Unknown host
ifconfig: `--help' gives usage information.
```
添加 `head -n 1` 使用第一个网卡可正常启动。
```
[root@xxx etc]# ifconfig `route|grep '^default'|awk '{print $NF}'|head -n 1`
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
...
```
**Special …
> 修复 agent 所在系统有多个网卡启动失败问题

- sql/n9e_mon.sql
添加索引，优化event_consumer处理速度
在event 表中数据很多（百万条）的时候，model.EventCnt 方法执行速度很慢，实际生产环境约五秒处理一条event，原因是方法中sql：（“where hashid = ? and event_type = ? and created between ? and ?”）,created字段没有加上索引，加上索引告警时间处理速度有显著提升
> "添加索引，优化event_consumer处理速度"

- config/config.go
- go.mod
- go.sum
1.  set Config.Heartbeat.LocalAddr when ip can not fetch by auto detect 
2.  upgrade snappy to v0.0.3 to avoid the following failure on Go 1.16
> Config.Heartbeat.LocalAddr  and arm build bug fix

- etc/server.yml
- go.mod
- go.sum
- src/modules/server/backend/init.go
- src/modules/server/backend/prom/api.go
- src/modules/server/backend/prom/data.go
- src/modules/server/backend/prom/metric.go
- src/modules/server/backend/prom/prom.go
- src/modules/server/backend/prom/query.go
- src/modules/server/backend/prom/read_client.go
- src/modules/server/backend/prom/write_client.go
- src/modules/server/config/config.go
- src/modules/server/server.go
1. 使用 remote write 接口写入,使用 prometheus http client 读取,支持 VictoriaMetric
2. 主程序入口添加 defer logger close, 保证缓冲区的日志不会丢失
3. 写入的指标带有默认前缀 [ n9e_metric_ ]
4. 特殊字符会被替换 [ . - / ]
5. 标签定义: 主机标签 endpoint. 节点标签 rdb_node_id
> ADD: 支持 prometheus 存储

- src/modules/server/cache/node.go
修复v4中告警策略设置排除节点后，导致该策略对节点下所有节点失效的问题
> 修复v4中告警策略设置排除节点后，导致该策略对节点下所有节点失效的问题

- src/pkg/ormx/types.go
使用pg数据库进行数据存储，pg会认为user表的contacts字段是string类型而json格式无法转换的问题
夜莺目前支持mysql和postgres，如果DBType使用postgres，用户管理和团队管理模块将无法正常使用
Fixes #
support postgres databse
> 兼容使用pg数据库，contacts字段json格式无法转换的问题

- src/server/router/router_openfalcon.go
- src/server/router/router_opentsdb.go
Two `err` variables in `src/server/router` were being lost because they were being reinitialized inside an if-block with a `:=`.
> src/server/router: fix clobbered errors

- src/pkg/ibex/ibex.go
This fixes an `err` variable in `src/pkg/ibex` that was being redeclared with an `:=` inside an `if` block and lost before it could be returned.
> src/pkg/ibex: fix dropped error

- src/webapi/router/router_builtin.go
fix
Fixes # 修复dashboard文件名被截断问题。xxx_by_business变成了xxx_by_busine
```
fmt.Println("TrimRight: ", strings.TrimRight("xxx_by_business.json", ".json"))
fmt.Println("TrimSuffix: ", strings.TrimSuffix("xxx_by_business.json", ".json"))
TrimRight:  xxx_by_busine
TrimSuffix:  xxx_by_business
```
> fix dashboard name

- src/server/router/router_opentsdb.go
- src/server/writer/writer.go
起因：我们遇到了多个几千个收集的targets，使得n9e发送到prometheus的效果不是很好。
想法：由于每个采集点都有一个ident，这样n9e处理的有些慢。
改造：默认提取ident，每个ident都有一个chan进行分发处理，提升消费效率。
> perf(opentsdb): 数据拉取以ident分发，并把list方式改为chan方式，提高消费效率。

- src/server/idents/idents.go
合并可以减少请求次数，其实并需要每个target_up都用一个ident的消费者去处理，这样会导致ident闲置时，每次只发1条数据到prometheus。
> perf: 合并targets_up指标为一个ident，减少资源利用。

- docker/n9eetc/script/notify/README.md
- docker/n9eetc/script/notify/notify.go
- etc/script/notify/README.md
- etc/script/notify/notify.go
- etc/server.conf
修复通过go plugin模式处理告警的时候的相关错误
错误如下：
2022-05-26 17:02:18.376607 ERROR engine/notify.go:425 failed to load caller: plugin: symbol n9eCaller not found in plugin plugin/unnamed-067de70ddf4feb0cb88dba22a1dc78d7e8da49bc
现象：提示找不到符号 n9eCaller 
解决方案：go plugin暴露的变量或函数必须以大写开头
> 修复go plugin相关错误

- src/models/alert_rule.go
Fixed a potential bug
In the added webapi of alertrule, the updated put request is not verified, making it problematic if there is a malicious data update
So I added a check on the rule
> fix alert put api not verify bug

- src/server/engine/worker.go
fix
例：
Promql: `cpu_usage_test1{cpu="cpu-total", ident="test-server1"} < 40`
执行频率60s, 持续时长180s，理论有3个点不满足条件会触发告警。
问题1：告警持续时间从0开始，要加上执行频率60
问题2: 180>180 结果为false，不会触发告警，需要改成>=
1.告警持续时间需要加上执行间隔。
2.告警持续判定>=
3.留观时长<
> fix ForDuration

- go.mod
fix: fix plugin error
在某些情况下，使用go plugin编译通知插件的时候，会因为使用的github.com/cespare/xxhash/v2 库版本问题，引发如下错误：
export GOPROXY=http://goproxy.cn,direct
go build -buildmode=plugin -o notify.so notify.go
asm: xxhash_amd64.s:120: when dynamic linking, R15 is clobbered by a global variable access and is used here: 00092 (/root/go/pkg/mod/github.com/cespare/xxhash/v2@v2.1.1/xxhash_amd64.s:120)       ADDQ    R15, AX
asm: assembly failed
make: *** [plugin] Error 2
该库主要由github.com/prometheus/client_golang 引用，升级该prometheus客户端版本，间接升级cespare/xxhash到 v2.1.2，即可解决该问题。
> fix: fix plugin error

- src/server/router/router.go
- src/server/router/router_memsto.go
feat
提供告警规则所属node查询接口，方便排查告警日志。
请求方式：
```
{
"id": "2",
"node": "xxx-ops-n9e-test01.bj+5428:19000"
}
```
> get alert-rule node

- docker/docker-compose.yaml
When i start up a docker-compose, then occured a prob without platform.
[Docker (Apple Silicon/M1 Preview) MySQL "no matching manifest for linux/arm64/v8 in the manifest list entries"]
Add the platform for mysql.
platform: linux/x86_64
> [fix] fix the docker problem of apple chip

- src/webapi/router/router_mw.go
修复使用proxyauth认证方式时，username ctx设置错误的bug
> fix proxy auth username error

- src/server/router/router_opentsdb.go
refactor: error info return
因为日志都是debug，所以在没开启debug的时候也应该让客户端知道错误的一些信息（否则服务端和客户端都不知道发生了什么），所以返回第一条错误信息到msg中给客户端。
> refactor: error info return

- src/models/recording_rule.go
1. 实际场景中会出现recordrule name相同的情况，所以这里关闭对同名recordrule的检查
> remove record rule check

- etc/server.conf
- go.mod
- go.sum
- src/models/relabel.go
- src/server/config/config.go
- src/server/writer/writer.go
feat
when we distribute to different tsdb, we may have different relabel policies for different tsdb; like prometheus relabel_config; that is what prometheus supports.
Fixes #
> feat: add write_relabel action before n9e remote writing to multi tsdb

- docker/Dockerfile
- docker/Dockerfile.goreleaser
1. 使用slim镜像作为基础镜像，打包后镜像大小约从 890M -> 290M
无法使用apline镜像，发送告警时会出现`x509: certificate signed by unknown authority response=`错误
> use slim base image

- src/models/user.go
bugfix
多字段更新用户时，参数作为slice接受，需要拆包之后再往下传入。该bug导致user.Update方法只能成功更新第一个参数对应的字段
无
> bug: user update by multifields, param need '...'

- src/server/common/conv/sample.go
FIX
__name__字段重复，导致无法写TSDB
```
2022-10-12 17:05:36.844801 WARNING writer/writer.go:80 example timeseries:labels:<name:"__name__" value:"cpu_zheng_test" > labels:<name:"__name__" value:"cpu_usage_idle" > labels:<name:"busigroup" value:"ops.test" > labels:<name:"cpu" value:"cpu-total" > labels:<name:"ident" value:"xxx-ops-n9e-test01.xxx" > labels:<name:"app" value:"1" > samples:<value:89.74012824976322 timestamp:1665565536844 >
```
> 修复记录规则不生效问题

- docker/n9eetc/script/notify/notify.go
- docker/n9eetc/server.conf
- docker/n9eetc/template/telegram.tpl
- docker/n9eetc/webapi.conf
- etc/script/notify/notify.go
- etc/server.conf
- etc/template/telegram.tpl
- etc/webapi.conf
- src/server/common/sender/telegram.go
- src/server/engine/notify.go
- src/server/engine/notify_maintainer.go
告警通知功能增强
增加了Telegram Bot通知的内置支持，具体的通知模板参考自企业微信机器人
Fixes #345
使用时，在用户的更多联系方式中，增加 telegram_robot_token 的配置项，值格式为 ”botToken/chatId“ ，也可以直接填入整个url链接，例如 ”https://api.telegram.org/botxxxx:xxxxxxxx/sendMessage?chat_id=123456“ ，支持url链接意味着使用方可以通过指定的自定义域名正向代理telegram官方api域名，从而达到国内正常使用的目的
我已经通过企业微信Bot的相关逻辑大概找了一些需要修改的地方，可能会有部分遗漏
>  feat: 添加Telegram Bot通知支持

- etc/webapi.conf
The `etc/webapi.conf` file contains typos that confuse first-time users in configuring SSO.
Fixes #
After configuring SSO login according to the /etc/webapi.conf example file, accessing the WEB login page will not show SSO login options, and accessing `<host>/api/n9e/auth/sso-config` through the API interface will return the message : 
```json
{"dat":{"oidcDisplayName":"", "casDisplayName":"", "oauthDisplayName":""}, "err":""}
```
After reviewing the [source code](https://github.com/ccfos/nightingale/blob/main/src/pkg/cas/cas.go#LL20C3-L20C3), I found a spelling error in the configuration file. Fixing this error will helpful for first-time users.
> fix: webapi conf sso section typo

- src/server/router/router_prom.go
采集端使用telegraf采集端时，主机标识为“host”，需改为“ident”
用[[outputs.http]]性能有较大提升(因使用protobuf)，telegraf配置段参考如下：
[[outputs.http]]
url = "http://n9e_ip/prometheus/v1/write"
data_format = "prometheusremotewrite"
[outputs.http.headers]
Content-Type = "application/x-protobuf"
Content-Encoding = "snappy"
X-Prometheus-Remote-Write-Version = "0.1.0"
> replace lable host to ident

- etc/server.conf
- src/server/common/label_append.go
- src/server/config/config.go
a new feature, target tags can rewrite labels defined in categraf config file
sometimes we want to modify labels which defined in client agent. but it is difficult as there is  so many client. Of course we can do this by salt or ansible. Currently, when the label on the target is the same as the label in the configuration file, the label in the configuration file prevails. With a few modifications, you can make the label on the target overwrite the label in the configuration file.
> target tags can rewrite labels deined in categraf config file

- src/models/alert_subscribe.go
- src/models/user.go
- src/server/common/sender/callback.go
- src/server/common/sender/dingtalk.go
- src/server/common/sender/email.go
- src/server/common/sender/feishu.go
- src/server/common/sender/mm.go
- src/server/common/sender/plugin.go
- src/server/common/sender/plugin_cmd_unix.go
- src/server/common/sender/plugin_cmd_windows.go
- src/server/common/sender/redis_pub.go
- src/server/common/sender/sender.go
- src/server/common/sender/telegram.go
- src/server/common/sender/webhook.go
- src/server/common/sender/wecom.go
- src/server/config/config.go
- src/server/engine/channel.go
- src/server/engine/consume.go
- src/server/engine/engine.go
- src/server/engine/logger.go
- src/server/engine/notify.go
- src/server/engine/notify_maintainer.go
- src/server/engine/route_strategy.go
- src/server/engine/sender.go
- src/server/engine/subscription.go
告警事件处理模块重构
添加订阅的Subscription抽象，用于维护告警的接收对象
添加router抽象、实现groupRouter等替换原来hardcode的发送逻辑
添加Sender抽象，重写原来的Sender
> feat: subscribe refactor

- src/server/router/router_prom.go
当原始指标同时存在host和ident标签或只存在host标签时，host会被ident重写
如下图：
> fix: host tag is overridden by ident

- src/pkg/cas/cas.go
解决cas3.0无法获取用户属性问题。
之前的代码加上path会变成 https://sso.xxx.cn/p3/login 导致无法登录。
```
[CAS]
Enable = true
DisplayName = "SSO登录"
SsoAddr = "https://sso.xxx.cn/p3" # cas3.0
RedirectURL = "https://test-monitor.xxx.cn/callback/cas"
CoverAttributes = true
DefaultRoles = ["Standard"]
[CAS.Attributes]
Nickname = "chinese_name"
Phone = "phone"
Email = "email"
```
> 修复cas登录无法获取用户属性

- docker/prometc/targets.json
"nwebapi:18000","nserver:19000" -> "n9e:17000"
Fixes #
> fix: prometheus job n9e's targets wrong

- docker/Dockerfile
- docker/Dockerfile.goreleaser
1.  python2 的基础镜像太老了，确少基础工具curl wget lsof，而且安装不便。python:3-slim 是基于 debian bullseye,安装基础工具方便，体积也不大
2.  integrations打包到基础镜像中，helm不需要通过configmap挂载icon等非txt格式的文件
Fixes #
> update docker image

- center/router/router_proxy.go
修复请求ES “跳过SSL验证” 选项勾选后没有生效的问题
增加了 TLSClientConfig 选项, 用于设置是否在http请求过程中验证证书
Fixes #1452 
**Special notes for your reviewer**: 已经在最新版本测试, 确认修改后, 可以正常查看ES数据
> 修复请求ES"跳过SSL验证"不生效问题

- alert/sender/dingtalk.go
钉钉markdown的文本里，消息文本后和@成员前加个换行，看起来更舒服些
当前：
```
规则标题: 内存使用量高于60%
监控指标: [rulename=内存使用量高于60% ]
恢复时间: 2023-04-11 16:23:41
发送时间: 2023-04-11 16:23:41 @群成员
```
> refactor: 优化钉钉通知被@时的排版

- alert/sender/mm.go
```
fix code
```
```
SendMM() may panic with illegal user token, just skip it.
Detail: illegal token makes url to nil, and url.RawQuery will panic.
```
```
no
```
```
no
```
> fix: sendmm run ok with illegal token

- docker/experience_pg_vm/initsql_for_postgres/a-n9e-for-Postgres.sql
fix: fix alert mute error for pg
fix error for "Scan error on column index 6, name "tags": Failed to unmarshal JSONB value"
修复告警屏蔽列表报错
> fix: fix alert mute error for pg

- models/alert_rule.go
host告警规则中，多个机器筛选条件，单个告警条件后，告警规则列表接口500
修复host告警规则中，queries多于triggers，FillSeverities方法中的数组越界导致panic的bug
Fixes #
> 修复获取告警规则列表 FillSeverities方法中的数组越界问题

- alert/dispatch/dispatch.go
- cli/upgrade/upgrade.sql
> feat: add ExtraSenders

- center/router/router_alert_subscribe.go
Fix the issue of partial fields failing to be updated in the alert subscription.
When I tried to update an incorrect alert subscription by clicking on the edit button, it seemed that there was an exceptional situation where the fields "prod" and "cate" were showing their previous values.
Add fields for updating subscription in func alertSubscribePut.
None
**Special notes for your reviewer**:  
None
> Fix an exception situation where the prod and cate fields cannot be updated

- center/center.go
- center/router/router.go
- center/router/router_heartbeat.go
**心跳上报时，增加更新update_at字段功能，使告警更加灵敏**
issue: [[关于心跳和机器失联告警的一些疑问](https://github.com/ccfos/nightingale/issues/1589#top)](https://github.com/ccfos/nightingale/issues/1589)
> heartbeat  update target table  update_at field

- pkg/i18nx/var.go
> optimize i18n format

- center/center.go
- center/router/router.go
- center/router/router_login.go
- etc/config.toml
- pkg/httpx/httpx.go
- pkg/secu/rsa.go
**新功能添加**
**登录密码添加RSA加密的选项**:
主要流程如下
**配置如下**:
```toml
[HTTP.RSA]
OpenRSA = false
RSAPublicKeyPath = "/etc/n9e/public.pem"
RSAPrivateKeyPath = "/etc/n9e/private.pem"
RSAPassWord = ""
```
> feat(Login): add rsa to password

- center/router/router.go
静态文件路由缺少了 ttf 类型的,导致本地开发会出现个错误
> add static ttf file route

- alert/mute/mute.go
- center/router/router.go
- center/router/router_alert_cur_event.go
- center/router/router_mute.go
- models/alert_cur_event.go
feat: add mute preview and an option to delete the active alerts
When creating a mute rule, allow a preview of the active alerts that will be matched, and provide an option to delete these active alerts with one click
Fixes [#1646](https://github.com/ccfos/nightingale/issues/1646)
> feat: add mute preview and an option to delete the active alerts

- center/router/router.go
- center/router/router_alert_cur_event.go
- models/alert_cur_event.go
Compute statistics for alert_cur_event & alert_his_event
Compute statistics for ‘Unresolved  alert events(total)’, ‘Alert events unresolved for more than 24 hours(total_24_ago)‘,
’Alert events received today(total_today, beginning of today)‘ and ‘Alert events received this week(total_week, monday of the current week, starting at 00:00)’
None
> Compute statistics for alert_cur_events

- alert/process/process.go
目前Targets cache刷新间隔默认9s
假如机器上报完成，9s之内 立刻有个告警触发，
此时获取缓存失败，*Processor.target  还是之前的target
> set target_ident when cache is not sync

- pkg/oauth2x/oauth2x.go
Oauth2 add debug log
Oauth2 add debug log for userInfo.
None.
> fix: oauth2 add debug log

- pkg/secu/rsa.go
This fixes an`err` variable clobbered by an `:=` inside an `if` block in `pkg/secu`.
> pkg/secu: fix dropped error

- prom/reader.go
This fixes two dropped `err` variables in the `prom` package.
> prom: fix dropped errors

- alert/eval/alert_rule.go
fix: alert eval query wrong datasource when add loki datasource and datasource set all
> fix: alert eval query wrong datasource when add loki datasource and datasource set all

- models/user.go
This fixes a spot in the `models` package where the use of `:=` inside an `if` block was preventing an `err` variable from being returned.
> models: fix clobbered error

- alert/eval/eval.go
fix bug
这段代码引用了一个nil的变量的方法，可能导致程序panic
Fixes #
可能需要把 astats 变量提升到 AlertRuleWorker 上来实现完整的指标统计
> fix: remove stats code that could cause panic

- pushgw/writer/stats.go
- pushgw/writer/writer.go
**fix: the relabeled labels were not updated to timeSeries, so pushgw's WriteRelabe does not work actually**
> Resolve a problem of pushgw  WriteRrelabel not working actually

- models/user.go
- pkg/ldapx/ldapx.go
- pkg/ldapx/user_sync.go
**Feature**
This PR introduces an automatic mapping of LDAP users to roles in Nightingale, significantly streamlining user management and ensuring that role assignments align with organizational policies. By leveraging LDAP group memberships or attributes, the system automatically assigns predefined roles in Nightingale, reducing the administrative burden and potential for human error.
N/A
Please review the included configuration settings below which detail how LDAP groups are mapped to Nightingale roles. Note that while RoleMapping has been implemented, TeamMapping is still pending and will be addressed in future updates.
```toml
Enable = true  # Enable LDAP authentication
Host = '127.0.0.1'  # LDAP server address
Port = 389  # LDAP server port
BaseDn = 'dc=demo,dc=com'  # LDAP base DN …
```
> Implement Automatic LDAP User to Nightingale Role Mapping

- models/user.go
- models/user_group_member.go
- pkg/ldapx/ldapx.go
- pkg/ldapx/user_sync.go
**What type of PR is this?**  
Feature
**What this PR does / why we need it:**  
This PR expands on the previously introduced LDAP-to-role mapping feature in Nightingale by implementing TeamMapping. This enhancement facilitates the automatic mapping of LDAP users not only to roles but also to specific teams based on their LDAP group memberships or attributes. It simplifies user and team management further, ensuring that both role and team assignments are consistent with organizational policies, thus reducing the administrative workload and minimizing human error.
**Which issue(s) this PR fixes:**  
N/A
**Special notes for your reviewer:**  
Please review the updated configuration settings below which now include detailed mappings for how LDAP groups and individual users are mapped to both …
> feature: Implement the team mapping function

- etc/config.toml
A slight errir that causes failure to set WriteRelabels.
> docs: fix wrong table name about 'WriteRelabels'

- alert/eval/eval.go
**对 prometheus 2.50.0 版本引入的 NewPossibleNonCounterInfo warnings 机制做适配**
https://github.com/prometheus/prometheus/pull/13022
可避免由于prom新版本对 metric name 的"软"规范问题 导致 夜莺跳过后续告警逻辑判定，从而导致预期外的异常 case；
> 对 prometheus 2.50.0 版本引入的 NewPossibleNonCounterInfo warnings 做适配

- center/cconf/conf.go
- center/router/router_alert_cur_event.go
- center/router/router_alert_his_event.go
- docker/compose-postgres/initsql_for_postgres/a-n9e-for-Postgres.sql
- docker/initsql/a-n9e.sql
- docker/migratesql/migrate.sql
- go.mod
- models/alert_cur_event.go
- models/alert_his_event.go
optimize
This PR enhances the functionality of the alert event filtering by allowing the use of multiple business group IDs. It includes logic to ensure that users can only view events for the business groups they belong to when the "view own business group events only" setting is enabled. This enhancement is necessary to provide more flexible and precise filtering options for alert events, improving the user experience and aligning with business requirements.
- The `getBusinessGroupIds` function has been updated to handle the filtering logic based on user business group membership and the `bgid` parameter from the frontend.
- This PR ensures that if …
> feat:  support event list view only by  business group

- alert/alert.go
- alert/dispatch/consume.go
This PR enhances the `consumeOne` method to handle the `recovery_promql` configuration. When an alert recovery event is detected, it parses the `recovery_promql` and executes the query to retrieve the corresponding recovery value. This value is then stored in the `AnnotationsJSON` field under the key `recovery_value`. This feature allows for more detailed and accurate alert recovery handling, providing important recovery metrics for further analysis.
The implementation involves:
- Parsing the `recovery_promql` from `AnnotationsJSON` and filling in the parameters.
- Executing the `recovery_promql` query when a recovery event is detected.
- Storing the …
> feature: the alert response event supports query recovery values

- alert/dispatch/dispatch.go
- alert/dispatch/notify_target.go
- alert/sender/callback.go
- alert/sender/dingtalk.go
- alert/sender/feishu.go
- alert/sender/feishucard.go
- alert/sender/ibex.go
- alert/sender/mm.go
- alert/sender/telegram.go
- alert/sender/wecom.go
- models/user.go
This PR simplifies the configuration of notification media for alert rules in Nightingale. Previously, users had to configure notification media separately, which was inconvenient and time-consuming. With this PR, users can directly configure the message dispatch to the desired notification media (such as DingTalk, Feishu, Feishu Card, WeCom, etc.) in the alert rule interface. This enhancement reduces the configuration cost and improves the user experience by providing a more streamlined and efficient setup process.
Please review the changes to ensure the new configuration interface is intuitive and user-friendly. Additionally, verify that the …
> feat: Callback operation adds IM connection function

- center/sso/init.go
/kind bug
When configCache is nil, in addition to printing the log, you also need to , otherwise the Get method will trigger a panic
Fixes #
> fix:get configcache return nil need exit

- integrations/Linux/alerts/常用中文告警规则-采集器Categraf.json
- integrations/Linux/metrics/categraf-base.json
更新默认报警规则中OOM 的检测语句。
kernel_vmstat_oom_kill 是一个累计值，系统启动后出现的OOM次数持续累计，原规则中的语句会导致持续报警，按increase更加合适。
间隔时间为2m，和 https://github.com/ccfos/nightingale/blob/f1259d1dffc2a6f247c99e3e8ef91d29fffe59c7/integrations/Linux/dashboards/host_generic_categraf.json#L1362 保持一致。
Fixes #
> update: oom_kill alert rule

- center/router/router_mute.go
- models/alert_mute.go
1. 告警屏蔽规则过期后不再清理，便于后续查看
2. 告警屏蔽规则同步时仅同步启用的规则
> alert mute retain

- alert/sender/email.go
修复新部署的服务修改 smtp 配置之后告警无法发送到邮箱的问题：
1. 旧 startEmailSender 需要等待新 startEmailSender 的信号再退出
> non buf channel happens-before

- alert/sender/callback.go
- alert/sender/dingtalk.go
- alert/sender/email.go
- alert/sender/feishu.go
- alert/sender/feishucard.go
- alert/sender/lark.go
- alert/sender/larkcard.go
- alert/sender/mm.go
- alert/sender/plugin.go
- alert/sender/telegram.go
- alert/sender/webhook.go
- alert/sender/wecom.go
- center/router/router_notification_record.go
> supplement noti records for agg events

- alert/eval/eval.go
> fix: alert rule check with var when not exact match

- center/router/router_target.go
- models/target.go
> get audit list by id

- alert/eval/eval.go
修复使用通配变量场景下，底层变量配置无法覆盖上层变量配置导致告警逻辑异常
> anomaly point key

- center/integration/init.go
允许用户设置变量 'disable_integration_init'，如果用户设置了这个变量，就会跳过 integration 初始化
> use config skip init integration

- alert/dispatch/dispatch.go
Rename `relaodTpls` to `reloadTpls`
> Typo: Rename relaodTpls to reloadTpls

- alert/eval/eval.go
- alert/process/process.go
- models/alert_rule.go
`alert/eval/eval.go` 中的 `severity` 变量默认值为 `0`，但从定义之后一直没有变更。按照上下文的逻辑，`severity` 的初始值应该设为 `4`，即最低优先级，然后在循环中如果碰到更高的优先级，则更新 `arw.Severity` 和 `severity`。
另外我发现 `arw.Severity` 变量一直没有使用，是否可以整个删除？还是有别的用处？
```go
func (arw *AlertRuleWorker) GetPromAnomalyPoint(ruleConfig string) ([]models.AnomalyPoint, error) {
var lst []models.AnomalyPoint
var severity int
// ......
arw.Inhibit = rule.Inhibit
for i, query := range rule.Queries {
if query.Severity < severity {
arw.Severity = query.Severity
}
// ......
}
```
在 `model/alert_rule.go` 中定义 Severity 常量。
```go
const (
SeverityEmergency = 1
SeverityWarning   = 2
SeverityNotice    = 3
SeverityLowest    = 4
)
```
修改 `alert/eval/eval.go` 中 `severity` 变量的初始化和变更逻辑。
```go
func (arw *AlertRuleWorker) GetPromAnomalyPoint(ruleConfig string) ([]models.AnomalyPoint, …
```
> fix alert rule worker severity

- models/alert_rule.go
fix (IMO)
This PR removes the existing `str.Dangerous` validation on rule names since it will reject valid Go templates because they may contain `"`. As an alternative, we will trim and try to compile the input as a template and reject if the compilation failed.
Fixes #
In a typical Elasticsearch use case, the tags and metrics are all JSON paths, which contains multiple `.` for nested access. This forbids us from accessing it via syntax like `{{$labels.host.name}}`, and we need to use `{{index $labels "host.name"}}`.
> fix: allow valid Go template as rule name

- center/router/router_board.go
当使用 id 和 ident 混合条件查询 Board 时，如果传入的参数为字符串（如 1abc），SQL 会将字符串隐式转换成整数进行比较，导致错误地查询出不相关的数据（例如输入 1abc 会返回 id=1 的记录）。
解决方案为先查询 indent，如果为空再查询 id
> fix: prevent incorrect board matches caused by implicit type casting

- center/router/router_user.go
- models/user.go
This PR introduces an optional `username` query parameter to the `GET /api/n9e/users` endpoint.
- If the `username` parameter is provided, the API returns only the user(s) matching the given username(s).
- Multiple usernames can be queried by providing a comma-separated string (e.g., `?username=admin,root`).
> feat: username query param for /api/n9e/users

- center/router/router.go
- center/router/router_mute.go
- center/router/router_target.go
1. 支持调用接口更新target
2. 支持模糊查询屏蔽策略,且不影响根据bgid查询全部
> feat: add target update

- datasource/commons/eslike/eslike.go
For logquery, using the from + size method is limited by the max_result_window parameter, while deep pagination is supported via search_after
> update(es):support search_after
